### ISSUE TITLE
[Bug]: 控制yeelight彩光灯泡开关报错

### ISSUE THREAD

**Issue by brucewzp** [XiaoMi/ha_xiaomi_home#106]
### Describe the bug / 描述问题

yeelight彩光灯泡 只能显示状态，无法控制开关，开关报错

### To Reproduce / 复现步骤

点击开关按钮报错
![image](https://github.com/user-attachments/assets/5b74c5f8-ef3c-4538-af39-7de411b51b31)

### Expected behavior / 预期结果

能够控制开关灯

### Home Assistant Logs / 系统日志

2024-12-17 20:39:30.086 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140486805234032] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 856, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 265, in async_turn_on
    result = await self.set_property_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prop=self._prop_on, value=value_on)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 860, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, 内部错误, light.yeelink_cn_46010513_color1_s_2,  灯, on

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by mrblueh** [comment]
我也是，我不管是yeelight彩光灯泡还是小米的吸顶灯，都提示内部错误

**Comment by zyq328328** [comment]
我也是，我所有的灯，都提示内部错误

**Comment by zacharywell** [comment]
一样的问题
