### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xuxjkl** [XiaoMi/ha_xiaomi_home#119]
### Describe the bug / 描述问题

登录账号后出现没有设备或实体

### To Reproduce / 复现步骤

![图片](https://github.com/user-attachments/assets/428812c7-a824-4cc8-812b-11f9e12e90ed)
[home-assistant_xiaomi_home_2024-12-17T14-21-32.800Z.log](https://github.com/user-attachments/files/18167018/home-assistant_xiaomi_home_2024-12-17T14-21-32.800Z.log)

### Expected behavior / 预期结果

登录成功并获取设备和实体

### Home Assistant Logs / 系统日志

2024-12-17 22:21:26.538 ERROR (1ced5bf3701af17a) [custom_components.xiaomi_home.miot.miot_client] 猫狗之家, mips try reconnect after 6000ms
2024-12-17 22:21:26.537 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 槿年: 1416218319 [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 619, in unit_convert
    'μS/cm': UnitOfConductivity.MICROSIEMENS_PER_CM,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core version / Home Assistant Core 版本

 Core 2024.10.1 

### Home Assistant Operation System version / Home Assistant Operation System 版本

 20241002.2 

### Xiaomi Home integration version / 米家集成版本

v0.1.1

**Comment by xuxjkl** [comment]
HA版本问题已解决

**Comment by wowton** [comment]
@xuxjkl 我也同样的报错，ha版本是2024.9.1，请问怎么解决的
