### ISSUE TITLE
[Bug]: viomi.waterheater.u12 热水器没有一键即热（预加热）功能

### ISSUE THREAD

**Issue by steinvenic** [XiaoMi/ha_xiaomi_home#150]
### Describe the bug / 描述问题

热水器没有一键即热（预加热）功能

### To Reproduce / 复现步骤

热水器没有一键即热（预加热）功能

### Expected behavior / 预期结果

有对应实体开关

### Home Assistant Logs / 系统日志

2024-12-18 14:21:29.821 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 14:21:29.823 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-18 14:22:19.193 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, miwifi.2dda930c-a97e-6e5e-bc71-ca01247c8e08
2024-12-18 14:22:19.194 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, miwifi.57a7c206-7d47-8f54-a285-68157a2bfc28
2024-12-18 14:22:30.128 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, miwifi.2dda930c-a97e-6e5e-bc71-ca01247c8e08
2024-12-18 14:22:30.128 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, miwifi.57a7c206-7d47-8f54-a285-68157a2bfc28
2024-12-18 14:22:32.855 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_spec] the language is not supported, zh-Hans, try using the default language, en, urn:miot-spec-v2:device:light:0000A001:miir-ir01:1
2024-12-18 14:22:34.563 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_spec] the language is not supported, zh-Hans, try using the default language, en, urn:miot-spec-v2:device:air-conditioner:0000A004:miir-ir02:1
2024-12-18 14:22:37.126 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_spec] the language is not supported, zh-Hans, try using the default language, en, urn:miot-spec-v2:device:water-heater:0000A02A:viomi-u12:1
2024-12-18 14:22:38.880 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_device] get_prop_value error, property is None,  热水器, water_heater.viomi_cn_458245448_u12_s_2
2024-12-18 14:22:38.881 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_device] get_prop_value error, property is None,  热水器, water_heater.viomi_cn_458245448_u12_s_2
2024-12-18 14:22:39.296 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['574344347|25|9', '574344347|25|7', '574344347|25|6', '574344347|25|5', '574344347|25|4', '574344347|25|3', '574344347|2|19', '585963896|6|1', '574344347|23|1']
2024-12-18 14:22:39.610 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback MIoTPropertyEntity.__write_ha_state_handler() (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 672, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: '40-70'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 675, in state
    numerical_value = float(value)
ValueError: could not convert string to float: '40-70'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1115, in __write_ha_state_handler
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 679, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.xiaomi_cn_574344347_m9_humidity_range_p_10_6 has device class 'None', state class 'None' unit '%' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '40-70' (<class 'str'>)
2024-12-18 14:22:39.881 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_device] get_prop_value error, property is None,  热水器, water_heater.viomi_cn_458245448_u12_s_2
2024-12-18 14:22:43.813 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['574344347|25|2', '574344347|25|1', '574344347|2|20', '464029062|3|20', '464029062|3|17', '464029062|3|14', '464029062|3|11', '464029062|3|8', '464029062|3|7', '464029062|3|6', '464029062|3|5', '464029062|3|4', '464029062|3|3', '585963896|3|3', '464029062|3|19', '464029062|3|18', '464029062|3|16', '464029062|3|15', '464029062|3|13', '464029062|3|12', '464029062|3|10', '464029062|3|9', '585963896|6|4', '464029062|6|6']
2024-12-18 14:22:44.335 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['585963896|3|1', '585963896|6|2', '585963896|6|3', '489544848|10|36']


### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

_No response_

**Comment by JimmyKmi** [comment]
参考 https://github.com/XiaoMi/ha_xiaomi_home/issues/17

**Comment by steinvenic** [comment]
> 参考 #17

并没有【一键即热】的开关
![image](https://github.com/user-attachments/assets/1ba9c760-cdf2-43b8-be9f-43e761cab456)

**Comment by SusanPhevos** [comment]
设备的[MIoT-Spec-V2](https://home.miot-spec.com/spec/viomi.waterheater.u12)工作状态不可写，只能作为Sensor显示。

**Comment by steinvenic** [comment]
> 设备厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/viomi.waterheater.u12)工作状态不可写，只能作为Sensor显示。

为什么非官方的`hass-xiaomi-miot`可以实现呢？不能控制设备，要这玩意还有何用？

**Comment by SusanPhevos** [comment]
> > 设备厂商定义的[MIoT-Spec-V2](https://home.miot-spec.com/spec/viomi.waterheater.u12)工作状态不可写，只能作为Sensor显示。
> 
> 为什么非官方的`hass-xiaomi-miot`可以实现呢？不能控制设备，要这玩意还有何用？

因为hass-xiaomi-miot用了一个MIoT-Spec-V2未定义的属性值，厂商隐藏该属性值可能有其特殊考虑，xiaomi_home无法保证使用该属性的可靠性和安全性。
