### ISSUE TITLE
[Bug]:Yeelight 皓石 LED吊灯 ---- light.yeelink_cn_582248838_ceiling10_s_2 无法开启

### ISSUE THREAD

**Issue by foxwywh** [XiaoMi/ha_xiaomi_home#159]
### Describe the bug / 描述问题

Yeelight 皓石 LED吊灯 wifi的，无法开启，查日志无相关内容

### To Reproduce / 复现步骤

能重复

### Expected behavior / 预期结果

尽快修复

### Home Assistant Logs / 系统日志

搜索相关日志，没有发现，只有以下提示： 
无法执行动作“light/turn_on” 。 执行错误, 内部错误, light.yeelink_cn_582248838_ceiling10_s_2, 灯, on

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

2024.12.3

### Xiaomi Home integration version / 米家集成版本

V0.1.0 V0.1.1

### Additional context / 其他说明

无

**Comment by topsworld** [comment]
您好，麻烦复现下提供ha的日志用于问题排查

**Comment by houfukude** [comment]
我来提供一下日志吧 @topsworld 

目前我手上两款 Yeelight 的吸顶灯(yeelink.light.ceiling23) (yeelink.light.ceiling22) 均无法控制  

```
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 855, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 566, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 265, in async_turn_on
    result = await self.set_property_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prop=self._prop_on, value=value_on)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 859, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, 内部错误, light.yeelink_cn_476314535_ceiling23_s_2,  灯, on

```
