### ISSUE TITLE
[Bug]: 米家智能宠物喂食器2 的“出粮”按钮被识别为了Notify

### ISSUE THREAD

**Issue by huahuahuahuahuahuahuahua** [XiaoMi/ha_xiaomi_home#161]
### Describe the bug / 描述问题

pet-food-out识别为了Notify类型

### To Reproduce / 复现步骤

Actions识别为了：

notify.xiaomi_cn_643788581_pi2001_pet_food_out_a_2_1 

### Expected behavior / 预期结果

应该为Button

### Home Assistant Core version / Home Assistant Core 版本

2024.6.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

Docker

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

Spec：

https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:pet-feeder:0000A06C:xiaomi-pi2001:1

**Comment by topsworld** [comment]
@huahuahuahuahuahuahuahua  您好，设计如此，米家中action中在ha中没有合适的实体，所以使用notify，可以打开action调试模式，会同步创建一个text实体

**Comment by huahuahuahuahuahuahuahua** [comment]
> @huahuahuahuahuahuahuahua 您好，设计如此，米家中action中在ha中没有合适的实体，所以使用notify，可以打开action调试模式，会同步创建一个text实体

你好，打开Debug模式之后，发送Command会失败(更新了HA到 2024.12.4）
我看Action描述里面参数是 [feeding-measure](https://miot-spec.org/miot-spec-v2/spec/property?type=urn:miot-spec-v2:property:feeding-measure:00000080) 
这个值可选是个数字，但是尝试输入1或者10之后会报以下错误

```
2024-12-18 11:57:19.429 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140268741570432] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 136, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params, {value}')
ValueError: action exec failed,  宠物喂食器 喂食机出粮(text.xiaomi_cn_643788581_pi2001_pet_food_out_a_2_1), invalid action params, 1
```

**Comment by huahuahuahuahuahuahuahua** [comment]
[1]

用这个发送可以了
