### ISSUE TITLE
[Bug]: lumi.airer.acn01 aqara晾衣架，无法控制。

### ISSUE THREAD

**Issue by haiyeung** [XiaoMi/ha_xiaomi_home#178]
### Describe the bug / 描述问题

lumi.airer.acn01 aqara晾衣架，无法控制。

### To Reproduce / 复现步骤

<img width="339" alt="image" src="https://github.com/user-attachments/assets/92c6d3cf-db10-4578-acfa-5f7b5b535c71" />

### Expected behavior / 预期结果

可以操控该设备。

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API ([文档](https://www.home-assistant.io/integrations/websocket_api), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
首次出现: 22:02:50 (2 次总计出现)
上次记录: 22:03:56

[140188080134112] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/xiaomi_home/number.py", line 106, in async_set_native_value
    await self.set_property_async(value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 内部错误, number.lumi_cn_85453992_acn01_target_position_p_2_2,  晾衣架 目标位置

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.0-v0.1.2

### Additional context / 其他说明

该设备可以更新状态，但是所有操作都不可用。

**Comment by haiyeung** [comment]
我发现其他设备的状态都可以获取，但是风扇、微波炉等设备无法控制。报错同上。灯具控制正常。

**Comment by topsworld** [comment]
您好，目前定位是局域网本地控制逻辑存在问题，可以试下将控制模式设置为云端，我们会在下个版本修复

**Comment by haiyeung** [comment]
感谢，确实去掉局域网卡的选项之后，可以控制了，希望尽快修复，谢谢！

**Comment by wozjs5** [comment]
> 您好，目前定位是局域网本地控制逻辑存在问题，可以试下将控制模式设置为云端，我们会在下个版本修复

请问如何将控制模式设置为云端，我的米家空调伴侣也出现了类似的问题
