### ISSUE TITLE
[Bug]: 米家空调伴侣2无法控制空调

### ISSUE THREAD

**Issue by wozjs5** [XiaoMi/ha_xiaomi_home#198]
### Describe the bug / 描述问题

米家空调伴侣2无法控制空调

### To Reproduce / 复现步骤

点击打开空调没有反应

### Expected behavior / 预期结果

修复该bug

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API (文档, 问题)
首次出现: 08:44:05 (1 次总计出现)
上次记录: 08:44:05

[547615665472] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 807, in async_handle_set_hvac_mode_service
    await self.async_set_hvac_mode(hvac_mode)
  File "/config/custom_components/xiaomi_home/climate.py", line 270, in async_set_hvac_mode
    await self.set_property_async(prop=self._prop_on, value=True)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, 内部错误, climate.lumi_cn_683206791_mcn02,  空调, on

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by al-one** [comment]
- https://github.com/XiaoMi/ha_xiaomi_home/issues/178#issuecomment-2551487081

**Comment by wozjs5** [comment]
> * [[Bug]: lumi.airer.acn01 aqara晾衣架，无法控制。 #178 (comment)](https://github.com/XiaoMi/ha_xiaomi_home/issues/178#issuecomment-2551487081)

将配置模式修改为云端后可以正常使用，感谢
