### ISSUE TITLE
[Bug]: xiaomi.router.rd03设备无法读取

### ISSUE THREAD

**Issue by chkdsk228** [XiaoMi/ha_xiaomi_home#219]
### Describe the bug / 描述问题

成功获取设备但是无法获得设备连接数和上传下载速度

### To Reproduce / 复现步骤

添加账号后可正常获取设备但是启用后无法获得设备连接数和上传下载速率。

### Expected behavior / 预期结果

成功获取设备三个参数

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home integration version / 米家集成版本

0.1.2

**Comment by SusanPhevos** [comment]
您好！请发一下设备详情页的截图及Home Assistant日志。

**Comment by chkdsk228** [comment]
<img width="1019" alt="image" src="https://github.com/user-attachments/assets/b622fcb4-0a2a-4a88-a93e-d5c40190fa07" />
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/3993d6a4-b2df-415f-bfa8-faa96c574666" />
因为显示为未知我就都取消启用了。刚看到你的消息我重新启用了一下显示为这样。

**Comment by moka12579** [comment]
> 您好！请发一下设备详情页的截图及Home Assistant日志。

我也有同样的问题，路由器状态未知
![9FF8C5B9-BCA6-432D-871E-CB2778F9A42B](https://github.com/user-attachments/assets/f0e64a6a-74f4-4783-a9ef-31ee8866230e)
![2ECEAF51-3597-43CE-88AF-1483DB8E2EAC](https://github.com/user-attachments/assets/5adb07c1-ec0b-4b48-bb33-cd8e524a945e)
![AB4C69D8-10BC-40AC-BC83-24F8A2EB0FE5](https://github.com/user-attachments/assets/00956b11-dab6-41e3-9d2e-efa53bbe76c5)

以下是操作路由器的日志

```

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245 
集成: Home Assistant WebSocket API (文档, 问题) 
首次出现: 2024年12月20日 21:43:11 (2 次总计出现) 
上次记录: 08:14:25

[547524773632] Unexpected exception
[547684018656] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 591, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 未知错误, code=-704002000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 97, in async_turn_on
    await self.set_property_async(value=True)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 未知错误, code=-704002000, switch.xiaomi_cn_miwifi_c813ee57_629e_8b7d_1629_1210ce86f17a_ra72_on_p_3_3,  WiFi管理 开关

```


更改配置后获取设备状态的日志

```

此错误来自自定义集成。

日志记录器: custom_components.xiaomi_home.miot.miot_client
来源: custom_components/xiaomi_home/miot/miot_client.py:1492 
集成: Xiaomi Home (文档, 问题) 
首次出现: 2024年12月20日 20:49:36 (4 次总计出现) 
上次记录: 08:16:46

refresh props failed, cloud, ['miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|9', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|10', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|15', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|16', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|18', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|14', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|17', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|9', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|10', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|11', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|12', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|13', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|3']

```

**Comment by shineanr** [comment]
同样的问题，状态都是未知，这是红米5400电竞版点击打开指示灯时候的错误，希望有帮助
![image](https://github.com/user-attachments/assets/c8bc84f8-03fd-40cd-a048-2fdb2b008153)

`2024-12-26 22:49:14.460 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472218706080] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 658, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 未知错误, code=-704002000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 265, in async_turn_on
    result = await self.set_property_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prop=self._prop_on, value=value_on)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, 未知错误, code=-704002000, light.xiaomi_cn_miwifi_31b8f26d_a5c1_bd4d_15c1_f17c0ca98652_rb04_s_5,  指示灯, on`

**Comment by SusanPhevos** [comment]
> > 您好！请发一下设备详情页的截图及Home Assistant日志。
> 
> 我也有同样的问题，路由器状态未知 ![9FF8C5B9-BCA6-432D-871E-CB2778F9A42B](https://private-user-images.githubusercontent.com/71615766/397893053-f0e64a6a-74f4-4783-a9ef-31ee8866230e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4ODIzODksIm5iZiI6MTczNTg4MjA4OSwicGF0aCI6Ii83MTYxNTc2Ni8zOTc4OTMwNTMtZjBlNjRhNmEtNzRmNC00NzgzLWE5ZWYtMzFlZTg4NjYyMzBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDA1MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMWNmMTRmYTMzYzhmODZhN2M4ZDVkOGEzN2M3OWQyNmNjMDNjMzhkMGIxODkyYjM1ZGZmMjhiYzIxNjI4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UHLxTBS8HsUy1BYLjVnD1kmL7S7-tjhgpnKjP0EvMbE) ![2ECEAF51-3597-43CE-88AF-1483DB8E2EAC](https://private-user-images.githubusercontent.com/71615766/397893057-5adb07c1-ec0b-4b48-bb33-cd8e524a945e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4ODIzODksIm5iZiI6MTczNTg4MjA4OSwicGF0aCI6Ii83MTYxNTc2Ni8zOTc4OTMwNTctNWFkYjA3YzEtZWMwYi00YjQ4LWJiMzMtY2Q4ZTUyNGE5NDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDA1MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMTUzZGZjZDA2NDEwZWY3NjViZjU4NjJjYTlkNTRkODE4NDFiZTgyMjE4YTQxZTc3NGUxZTQ1ZWY4YTc2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o7LqsiDvNO-NLbKI6N5CbY_Uhcb47Z7nqR9kAMjcJsg) ![AB4C69D8-10BC-40AC-BC83-24F8A2EB0FE5](https://private-user-images.githubusercontent.com/71615766/397893058-00956b11-dab6-41e3-9d2e-efa53bbe76c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4ODIzODksIm5iZiI6MTczNTg4MjA4OSwicGF0aCI6Ii83MTYxNTc2Ni8zOTc4OTMwNTgtMDA5NTZiMTEtZGFiNi00MWUzLTlkMmUtZWZhNTNiYmU3NmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDA1MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYzFhMmI1NjdkYjBkNmQ1OThjNjA1NzgxYjlhMGRlMWNkYTNkOTUzYjE5ZGM5ZDdkODk0NTNjMGQ0MTZiNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.49ZkKgd4xP59jx7ALHyeboIy0mxupWUHygYP65cjV4s)
> 
> 以下是操作路由器的日志
> 
> ```
> 
> 日志记录器: homeassistant.components.websocket_api.http.connection
> 来源: components/websocket_api/commands.py:245 
> 集成: Home Assistant WebSocket API (文档, 问题) 
> 首次出现: 2024年12月20日 21:43:11 (2 次总计出现) 
> 上次记录: 08:14:25
> 
> [547524773632] Unexpected exception
> [547684018656] Unexpected exception
> Traceback (most recent call last):
>   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
>     await self.miot_device.miot_client.set_prop_async(
>         did=self.miot_device.did, siid=self.spec.service.iid,
>         piid=self.spec.iid, value=value)
>   File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 591, in set_prop_async
>     raise MIoTClientError(
>         self.__get_exec_error_with_rc(rc=rc))
> custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 未知错误, code=-704002000
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
>     response = await hass.services.async_call(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<7 lines>...
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>         hass, entity, func, data, call.context
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/config/custom_components/xiaomi_home/switch.py", line 97, in async_turn_on
>     await self.set_property_async(value=True)
>   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
>     raise RuntimeError(
>         f'{e}, {self.entity_id}, {self.name}') from e
> RuntimeError: 执行错误, 未知错误, code=-704002000, switch.xiaomi_cn_miwifi_c813ee57_629e_8b7d_1629_1210ce86f17a_ra72_on_p_3_3,  WiFi管理 开关
> ```
> 
> 更改配置后获取设备状态的日志
> 
> ```
> 
> 此错误来自自定义集成。
> 
> 日志记录器: custom_components.xiaomi_home.miot.miot_client
> 来源: custom_components/xiaomi_home/miot/miot_client.py:1492 
> 集成: Xiaomi Home (文档, 问题) 
> 首次出现: 2024年12月20日 20:49:36 (4 次总计出现) 
> 上次记录: 08:16:46
> 
> refresh props failed, cloud, ['miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|9', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|10', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|15', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|5|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|5', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|6', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|7', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|16', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|18', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|14', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|17', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|3', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|4', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|8', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|9', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|10', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|11', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|12', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|2|13', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|1', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|3|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|2', 'miwifi.c813ee57-629e-8b7d-1629-1210ce86f17a|4|3']
> ```

经路由器团队确认，该路由器虽然定义了 MIoT-Spec-V2，但设备固件并未实现 MIoT-Spec-V2 功能，故无法通过 MIoT-Spec-V2 控制设备、读取信息。下一版我们将把所有未实现 MIoT-Spec-V2 的路由器从可导入的设备列表中剔除。

**Comment by SusanPhevos** [comment]
> <img alt="image" width="1019" src="https://private-user-images.githubusercontent.com/22486589/397675022-b622fcb4-0a2a-4a88-a93e-d5c40190fa07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4ODIzODksIm5iZiI6MTczNTg4MjA4OSwicGF0aCI6Ii8yMjQ4NjU4OS8zOTc2NzUwMjItYjYyMmZjYjQtMGEyYS00YTg4LWE5M2UtZDVjNDAxOTBmYTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDA1MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTg4MTYyOWYzMzY0MDRiZjVhMDgwMWQwODVkZDIxNjJhNzQzN2VjMDlmNTAyMGYxMThkMjYwODFiNzAzMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3WnwXIAX-Ln4KDslx9Y8GKs6C7--lrqLsMieSeAaaXo"> <img alt="image" width="1103" src="https://private-user-images.githubusercontent.com/22486589/397675065-3993d6a4-b2df-415f-bfa8-faa96c574666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4ODIzODksIm5iZiI6MTczNTg4MjA4OSwicGF0aCI6Ii8yMjQ4NjU4OS8zOTc2NzUwNjUtMzk5M2Q2YTQtYjJkZi00MTVmLWJmYTgtZmFhOTZjNTc0NjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDA1MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5OTBkMDg2ZWZkYWQ5YjM2MjBhNDAwN2ExN2VjMTYxNGRiMzM2NWY5YmI0MWI5MDY1OWE0YjA4MjllN2UyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VERt5j5Ss079t-GvvARayS0jnABngNao02hZMOykx78"> 因为显示为未知我就都取消启用了。刚看到你的消息我重新启用了一下显示为这样。

你对这款路由器应该实现了 MIoT-Spec-V2 功能，请您请将日志等级设置为debug级别（方法详见[这里）](https://github.com/XiaoMi/ha_xiaomi_home/blob/main/doc/CONTRIBUTING_zh.md#%E6%88%91%E5%8F%AF%E4%BB%A5%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE)，重新导入一遍路由器，并上传HA日志。如果您担心隐私问题，可将日志发送至 ha_xiaomi_home@xiaomi.com ，邮件正文附上此 issue 的链接。

**Comment by chkdsk228** [comment]
额，我不太会配置，算了问题不大。这个问题对我日常使用影响不是很大。
