### ISSUE TITLE
[Bug]: 获取家庭失败

### ISSUE THREAD

**Issue by xdatoutou** [XiaoMi/ha_xiaomi_home#22]
### Describe the bug / 描述问题

添加账号时，提示获取家庭失败。另一个小米账号就可以

### To Reproduce / 复现步骤

1.添加集成
2.点击登陆
3.提示获取家庭失败

### Expected behavior / 预期结果

能正常获取家庭和设备

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

V0.1.0

### Additional context / 其他说明

![image](https://github.com/user-attachments/assets/39e6f4fd-a163-45eb-9ffc-187be96f75eb)

**Comment by topsworld** [comment]
您好，麻烦帮忙复现下，然后提供下ha的日志

**Comment by xdatoutou** [comment]
米家ID:26174026


以下是日志


联系电话：18620362512








以上的HA的日志
===============================================


以下是获取家庭请求的抓包







以下是响应数据

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XiaoMi/ha_xiaomi_home"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XiaoMi/ha_xiaomi_home] [Bug]: 获取家庭失败 (Issue #22)





 
您好，麻烦帮忙复现下，然后提供下ha的日志

**Comment by xdatoutou** [comment]
邮件回复居然没有图片。我重新发

![image](https://github.com/user-attachments/assets/a5706feb-8a42-4ae8-a682-98b386e6f2f8)
![image](https://github.com/user-attachments/assets/f76fb8ce-9ecd-4745-9691-4e7c3ca9f908)
![image](https://github.com/user-attachments/assets/19f00b12-c09d-44ba-afca-a20dab7ff826)
![image](https://github.com/user-attachments/assets/43f843b3-25dd-40d0-8aa2-c3eedd218642)

**Comment by xdatoutou** [comment]
> 您好，麻烦帮忙复现下，然后提供下ha的日志

已经在评论区贴上日志了

**Comment by xdatoutou** [comment]
> 您好，麻烦帮忙复现下，然后提供下ha的日志

加上debug日志


2024-12-17 04:13:20.852 DEBUG (MainThread) [homeassistant.components.http.auth] Authenticated 192.168.50.144 for /api/config/config_entries/flow/01JF9CJGR61FGTVKTA3WZJ6M57 using bearer token
2024-12-17 04:13:20.853 DEBUG (MainThread) [homeassistant.helpers.http] Serving /api/config/config_entries/flow/01JF9CJGR61FGTVKTA3WZJ6M57 to 192.168.50.144 (auth: True)
2024-12-17 04:13:20.853 ERROR (MainThread) [custom_components.xiaomi_home.config_flow] task_oauth exception, get_homeinfo_error

**Comment by xdatoutou** [comment]
> 您好，麻烦帮忙复现下，然后提供下ha的日志

定位到错误原因了，不知道为什么有一个特殊的房间，没有名称(room_name)，我在米家APP没看到这个房间


2024-12-17 04:59:48.426 INFO (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] {'room_id': '977001070798', 'room_name': '走道', 'dids': ['1024816476', '317114286', '71509152', '71724398', '71833593', '91439031', 'lumi.158d0004071c92', 'lumi.158d0004071c92.s2', 'lumi.158d0004071c92.s3', 'lumi.158d00040906cb.s2', 'lumi.158d00040906cb.s3', 'lumi.158d00040908fa.s2', 'lumi.158d00040908fa.s3']}
2024-12-17 04:59:48.426 INFO (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get room_info aaa, {'dids': ['proxy.70022213109.2.61765779']}
2024-12-17 04:59:48.426 INFO (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] {'dids': ['proxy.70022213109.2.61765779']}
2024-12-17 04:59:48.434 ERROR (MainThread) [custom_components.xiaomi_home.config_flow] get_homeinfos error 111, 'room_name', Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/config_flow.py", line 364, in __check_oauth_async
    await self._miot_http.get_devices_async())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 625, in get_devices_async
    room_id] = room_info['room_name']
               ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'room_name'

**Comment by topsworld** [comment]
感谢，问题定位了，我们安排修复

**Comment by topsworld** [comment]
v0.1.1版本已修复，如果问题仍存在，可reopen
