### ISSUE TITLE
[Bug]: ModuleNotFoundError Platform xiaomi_home.climate not found

### ISSUE THREAD

**Issue by rigel0212** [XiaoMi/ha_xiaomi_home#226]
### Describe the bug / 描述问题

无法添加设备

### To Reproduce / 复现步骤

日志记录器: homeassistant.config_entries
来源: config_entries.py:640
首次出现: 14:21:35 (1 次总计出现)
上次记录: 14:21:35

Error setting up entry Rigel: 1332601711 [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 226, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(
        config_entry, SUPPORTED_PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1123, in async_get_platforms
    if platform := self._get_platform_cached_or_raise(platform_name):
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1214, in _get_platform_cached_or_raise
    raise ModuleNotFoundError(
    ...<2 lines>...
    )
ModuleNotFoundError: Platform xiaomi_home.climate not found

### Expected behavior / 预期结果

无法添加

### Home Assistant Logs / 系统日志

![Uploading screenshot-20241219-135810.png…]()


### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

14

### Xiaomi Home integration version / 米家集成版本

v0.1.2

### Additional context / 其他说明

_No response_

**Comment by rigel0212** [comment]
重新安装插件，莫名其妙就好了。。。
