### ISSUE TITLE
[Bug]: yeelight风扇灯实体功能异常

### ISSUE THREAD

**Issue by uronn** [XiaoMi/ha_xiaomi_home#230]
### Describe the bug / 描述问题

风扇灯识别后，在风扇实体里，调风速不生效

### To Reproduce / 复现步骤

设备识别型号：yeelink.light.fancl5
实体标识符：yeelink_cn_360750458_fancl5_s_3
![image](https://github.com/user-attachments/assets/6b8914e0-c970-41a1-ab18-d7ea69d95acd)

但是在miot auto里，使用正常：
实体标识符：yeelink_fancl5_c40f_fan
![image](https://github.com/user-attachments/assets/fd1439b9-d066-436d-b2e0-68ccb6d9ba7a)

### Expected behavior / 预期结果

风扇灯的风扇可以调风速

### Home Assistant Logs / 系统日志

无

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

无

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by zacharywell** [comment]
yeelink吸顶灯也异常，只能查看状态无法控制

**Comment by SusanPhevos** [comment]
您好！请发一下问题复现时的Home Assistant日志。

**Comment by zacharywell** [comment]
> 您好！请发一下问题复现时的Home Assistant日志。
这是吸顶灯的日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API ([文档](https://www.home-assistant.io/integrations/websocket_api), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
首次出现: 2024年12月19日 21:27:11 (16 次总计出现)
上次记录: 07:46:06

[140066366419392] Unexpected exception
[140066383861440] Unexpected exception
[140066366408592] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 639, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 299, in async_turn_off
    return await self.set_property_async(prop=self._prop_on, value=value_on)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, 内部错误, light.yeelink_cn_647424166_ceiling23_s_2,  灯, on

**Comment by wozjs5** [comment]
> > 您好！请发一下问题复现时的Home Assistant日志。
> > 这是吸顶灯的日志
> 
> 日志记录器: homeassistant.components.websocket_api.http.connection 来源: components/websocket_api/commands.py:245 集成: Home Assistant WebSocket API ([文档](https://www.home-assistant.io/integrations/websocket_api), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 首次出现: 2024年12月19日 21:27:11 (16 次总计出现) 上次记录: 07:46:06
> 
> [140066366419392] Unexpected exception [140066383861440] Unexpected exception [140066366408592] Unexpected exception Traceback (most recent call last): File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async await self.miot_device.miot_client.set_prop_async( did=self.miot_device.did, siid=prop.service.iid, piid=prop.iid, value=value) File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async raise MIoTClientError( self.__get_exec_error_with_rc(rc=rc)) custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service response = await hass.services.async_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<7 lines>... ) ^ File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call response_data = await coro ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service return await target(service_call) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call single_response = await _handle_entity_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^ hass, entity, func, data, call.context ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call result = await task ^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/components/light/**init**.py", line 639, in async_handle_light_off_service await light.async_turn_off(**filter_turn_off_params(light, params)) File "/config/custom_components/xiaomi_home/light.py", line 299, in async_turn_off return await self.set_property_async(prop=self._prop_on, value=value_on) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async raise RuntimeError( f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e RuntimeError: 执行错误, 内部错误, light.yeelink_cn_647424166_ceiling23_s_2, 灯, on

考虑将配置模式暂时修改为云端，我的空调伴侣也是同样的报错，

**Comment by uronn** [comment]
> 您好！请发一下问题复现时的Home Assistant日志。

这个问题在新版本仍未解决：
yeelink_cn_360750458_fancl5_s_3，这个实体下，滑块无法控制风速，开关和模式切换功能是正常的：
![image](https://github.com/user-attachments/assets/06dc30b0-8de0-4b73-9865-88dfd17175f9)

yeelink_cn_360750458_fancl5_fan_speed_std_p_5_7，这个单独的风速实体可以控制

日志如下：

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/fan.py", line 205, in async_set_percentage
    await self.set_property_async(
    ...<3 lines>...
            percentage=percentage)))
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, Property值错误, fan.yeelink_cn_360750458_fancl5_s_6,  风扇, fan-level
2024-12-25 09:39:02.269 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall fan.set_percentage (c:01JFXQF8YGPY7RN6V2F6CWV1SQ): entity_id=['fan.yeelink_cn_360750458_fancl5_s_6'], percentage=21>
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 658, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, Property值错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/fan.py", line 205, in async_set_percentage
    await self.set_property_async(
    ...<3 lines>...
            percentage=percentage)))
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 871, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}, {prop.name}') from e
RuntimeError: 执行错误, Property值错误, fan.yeelink_cn_360750458_fancl5_s_6,  风扇, fan-level
2024-12-25 09:39:08.213 ERROR (22f12ae324173464) [custom_components.xiaomi_home.miot.miot_client] 金域蓝湾, mips try reconnect after 60000ms
2024-12-25 09:39:21.229 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall fan.set_percentage (c:01JFXQFVC4G50TAVKAJDQGRKSR): entity_id=['fan.yeelink_cn_360750458_fancl5_s_6'], percentage=21>
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 658, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, Property值错误
