### ISSUE TITLE
[Bug]: 开启本地模式后小米智能插座usb版 chuangmi.plug.v3 无法开关

### ISSUE THREAD

**Issue by congzhengmian** [XiaoMi/ha_xiaomi_home#242]
### Describe the bug / 描述问题

开启本地模式后小米智能插座usb版 chuangmi.plug.v3 无法开关

### To Reproduce / 复现步骤

更新局域网控制配置后该插座无法被控制。

### Expected behavior / 预期结果

应当可以操作开关

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API ([文档](https://next.home-assistant.io/integrations/websocket_api), [问题](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
首次出现: 18:24:22 (6 次总计出现)
上次记录: 18:27:07

[139649092346944] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1066, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 567, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 内部错误

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1006, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1078, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 101, in async_turn_off
    await self.set_property_async(value=False)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1070, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 内部错误, switch.chuangmi_cn_119125508_v3_on_p_2_1,  开关 电源

### Home Assistant Core version / Home Assistant Core 版本

2025.1.0.dev202412160236

### Home Assistant Operation System version / Home Assistant Operation System 版本

20241216.0.dev

### Xiaomi Home integration version / 米家集成版本

v0.1.0

**Comment by JimmyKmi** [comment]
提 issue 之前请看 readme！！

中枢网关本地固件暂未推送，不支持本地。等待中枢固件开发完成会支持。
