### ISSUE TITLE
[Bug]: Readmi路由器AX6S xiaomi.router.rb03 有线中继模式 传感器状态全是未知

### ISSUE THREAD

**Issue by itning** [XiaoMi/ha_xiaomi_home#244]
### Describe the bug / 描述问题

有线中继模式 传感器状态全是未知

### To Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/0a32217e-8453-445d-aa5c-d1153b9d0ef1)

### Expected behavior / 预期结果

路由器 工作状态 之类的应该有值

### Home Assistant Logs / 系统日志

```
2024-12-19 10:18:59.600 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-19 10:18:59.601 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-19 10:18:59.602 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deye_dehumidifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-19 10:19:01.854 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f6131c3ea80>,) inside the event loop by custom integration 'deye_dehumidifier' at custom_components/deye_dehumidifier/__init__.py, line 60: mqtt_client = DeyeMqttClient( (offender: /usr/local/lib/python3.13/site-packages/paho/mqtt/client.py, line 806: context.load_default_certs()), please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/deye_dehumidifier/__init__.py", line 60, in async_setup_entry
    mqtt_client = DeyeMqttClient(

2024-12-19 10:19:03.312 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|13', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|12', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|11', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|10', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|9', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|17', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|14', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|18', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|16', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|15', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|10', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|9', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|3', '567179306|6|1', '567179306|6|3', '567179306|6|2', '567179306|3|3', '567179306|6|4']
2024-12-19 10:19:03.859 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'deye_dehumidifier' accesses hass.helpers.event, which should be updated to import functions used from event directly at custom_components/deye_dehumidifier/humidifier.py, line 85: self.hass.helpers.event.async_track_time_interval(. This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/stackia/ha-deye-dehumidifier/issues
2024-12-19 10:19:04.531 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['335328610|3|2']
2024-12-19 15:03:35.962 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips disconnect, 16, None
2024-12-19 15:03:35.966 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips try reconnect after 30000ms
2024-12-19 15:03:35.969 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips try reconnect after 60000ms
2024-12-19 15:03:35.971 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/519670622/up/properties_changed/#
2024-12-19 15:03:35.972 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/519670622/up/event_occured/#
2024-12-19 15:03:35.978 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/335328610/up/properties_changed/#
2024-12-19 15:03:35.979 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/335328610/up/event_occured/#
2024-12-19 15:03:35.983 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/362270595/up/properties_changed/#
2024-12-19 15:03:35.983 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/362270595/up/event_occured/#
2024-12-19 15:03:35.987 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/567179306/up/properties_changed/#
2024-12-19 15:03:35.988 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/567179306/up/event_occured/#
2024-12-19 15:03:35.992 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/731383025/up/properties_changed/#
2024-12-19 15:03:35.993 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/731383025/up/event_occured/#
2024-12-19 15:03:35.996 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/731875857/up/properties_changed/#
2024-12-19 15:03:35.997 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/731875857/up/event_occured/#
2024-12-19 15:03:36.001 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/746347738/up/properties_changed/#
2024-12-19 15:03:36.001 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/746347738/up/event_occured/#
2024-12-19 15:03:36.005 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/747613037/up/properties_changed/#
2024-12-19 15:03:36.005 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/747613037/up/event_occured/#
2024-12-19 15:03:36.009 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/749231544/up/properties_changed/#
2024-12-19 15:03:36.009 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/749231544/up/event_occured/#
2024-12-19 15:03:36.012 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/blt.3.13c43sqtceg00/up/properties_changed/#
2024-12-19 15:03:36.012 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/blt.3.13c43sqtceg00/up/event_occured/#
2024-12-19 15:03:36.016 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66/up/properties_changed/#
2024-12-19 15:03:36.017 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66/up/event_occured/#
2024-12-19 15:03:36.022 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/blt.3.1ifsk4lfs4c05/up/properties_changed/#
2024-12-19 15:03:36.022 ERROR (ha.5d3b6ed2e818db940c8b568d6fe27ae7) [custom_components.xiaomi_home.miot.miot_client] ha.5d3b6ed2e818db940c8b568d6fe27ae7, mips unsub internal error, 4, None, device/blt.3.1ifsk4lfs4c05/up/event_occured/#
2024-12-19 15:04:38.241 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|13', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|12', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|11', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|10', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|9', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|17', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|14', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|18', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|16', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|3', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|15', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|2|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|10', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|9', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|4|6', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|8', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|3|7', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|4', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|5', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|2', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|1', 'miwifi.10067e2d-8b7c-cc20-832d-613df9c5df66|5|3', '567179306|6|1', '567179306|6|3', '567179306|6|2', '567179306|3|3', '567179306|6|4']
2024-12-19 15:04:39.875 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['335328610|3|2']
2024-12-19 15:06:43.882 ERROR (MainThread) [custom_components.deye_dehumidifier.data_coordinator] Timeout fetching deye_data_update_coordinator data
2024-12-19 19:07:07.857 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140055210775824] from 192.168.10.28 (Home Assistant/2024.12.1 (io.robbie.HomeAssistant; build:2024.1041; iOS 18.2.0)): Disconnected: Did not receive auth message within 10 seconds

```

### Home Assistant Core version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System version / Home Assistant Operation System 版本

14.0

### Xiaomi Home integration version / 米家集成版本

v0.1.2

**Comment by SusanPhevos** [comment]
经路由器团队确认，该路由器虽然定义了 MIoT-Spec-V2，但设备固件并未实现 MIoT-Spec-V2 功能，故无法通过 MIoT-Spec-V2 控制设备、读取信息。下一版我们将把所有未实现 MIoT-Spec-V2 的路由器从可导入的设备列表中剔除。
