### ISSUE TITLE
[Bug]: 安装报错（无法加载配置向导: {"message":"Invalid handler specified"}）

### ISSUE THREAD

**Issue by WangNingkai** [XiaoMi/ha_xiaomi_home#28]
### Describe the bug / 描述问题

无法加载配置向导: {"message":"Invalid handler specified"}

### To Reproduce / 复现步骤

已按步骤运行添加到hass，开始配置出现错误

### Expected behavior / 预期结果

安装成功

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.loader
来源: loader.py:1271
首次出现: 00:07:44 (8 次总计出现)
上次记录: 00:21:22

Unexpected exception importing platform custom_components.xiaomi_home.config_flow
Traceback (most recent call last):
  File "/Users/wangningkai/.local/pipx/venvs/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/Users/wangningkai/.local/pipx/venvs/homeassistant/lib/python3.13/site-packages/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wangningkai/.local/pipx/venvs/homeassistant/lib/python3.13/site-packages/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.13/3.13.1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/wangningkai/.homeassistant/custom_components/xiaomi_home/__init__.py", line 64, in <module>
    from .miot.miot_device import MIoTDevice
  File "/Users/wangningkai/.homeassistant/custom_components/xiaomi_home/miot/miot_device.py", line 90, in <module>
    from .miot_client import MIoTClient
  File "/Users/wangningkai/.homeassistant/custom_components/xiaomi_home/miot/miot_client.py", line 24, in <module>
    from .miot_mips import (
        MIoTDeviceState, MipsCloudClient, MipsDeviceState,
        MipsLocalClient)
  File "/Users/wangningkai/.homeassistant/custom_components/xiaomi_home/miot/miot_mips.py", line 301, in <module>
    class MipsClient(ABC):
    ...<679 lines>...
            return self._mips_reconnect_interval
  File "/Users/wangningkai/.homeassistant/custom_components/xiaomi_home/miot/miot_mips.py", line 333, in MipsClient
    _cmd_event_fd: os.eventfd
                   ^^^^^^^^^^
AttributeError: module 'os' has no attribute 'eventfd'

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

core版本

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

_No response_

**Comment by IamIpanda** [comment]
同样的问题。
使用的docker版HA。

**Comment by KyoMio** [comment]
同样的问题，docker版本的ha，core版本2023.11.3

**Comment by yichengchen** [comment]
docker 升级到2024.11即可

**Comment by KyoMio** [comment]
> @KyoMio docker 的ha升级到2024.12即可

感谢，已更新，能正常使用了。

**Comment by 826541814** [comment]
> @KyoMio docker 的ha升级到2024.12即可

设备为极空间NAS，环境为docker， ha版本为 2024.12， 同样出现了无法加载配置向导的问题
<img width="683" alt="image" src="https://github.com/user-attachments/assets/7f903ed6-cb47-4988-96f1-82370f1c94e6" />
<img width="494" alt="image" src="https://github.com/user-attachments/assets/d39bf0ac-0f2f-45a2-9b84-4a93fca9ac29" />

**Comment by sidlehui** [comment]
> 我装的就是最新的 **2024.12.3**，不行唉，环境**python3.13**

same here, same python3.13 core 2024.12.5

**Comment by topsworld** [comment]
已切换asyncio，麻烦使用v0.1.5b1验证下。
