### ISSUE TITLE
多个家庭选择时，有的家庭可以直接添加成功并且可以控制使用，有的家庭添加后瞬间退出自动重启

### ISSUE THREAD

**Issue by symi-daguo** [XiaoMi/ha_xiaomi_home#285]
### Describe the Bug / 描述问题

如果先选择可以控制的房间进入集成控制后，再替换成无法添加的那个家庭，一旦替换后ha就无限重启，日志也看不到，需要进入文件夹把插件删除

### How to Reproduce / 复现步骤

1、添加米家集成，输入账号密码，选择需要的家庭；
2、多个家庭选择其中一个可能能正常添加控制，可能不能控制直接退出插件；
3、添加可以控制的家庭，再进去替换成不可以添加的家庭就导致ha无限重启；
4、进入文件夹后台，进去删除组件恢复正常；

### Expected Behavior / 预期结果

找到不可添加的原因和导致ha无限重启的原因

### Home Assistant Logs / 系统日志

2024-12-20 16:50:38.092 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Integration 'xiaomi_home' not found.
2024-12-20 16:50:38.677 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2024-12-20 16:50:38.759 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=247 from 2024-12-20 08:39:37.550247)
2024-12-20 16:50:43.848 ERROR (MainThread) [homeassistant.setup] Setup failed for 'xiaomi_home': Integration not found.
2024-12-20 16:50:51.633 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140561554064288] Error handling message: Unknown error (unknown_error) hasskit from 192.168.2.37 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 537, in handle_manifest_list
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'xiaomi_home' not found.
2024-12-20 16:50:58.747 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp32-zhonghong @ 192.168.2.15: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.2.15', port=6053))]: [Errno 111] Connect call failed ('192.168.2.15', 6053) (SocketAPIError)
2024-12-20 16:51:05.153 WARNING (MainThread) [homeassistant.components.homekit] HomeKit HASS Bridge cannot add device 726806d2b06f6e42b52629ccf6eae207 because it is missing from the device registry
2024-12-20 16:51:05.153 WARNING (MainThread) [homeassistant.components.homekit] HomeKit HASS Bridge cannot add device 6866e77b92841abc5a8a67689a0f3687 because it is missing from the device registry
2024-12-20 16:51:05.154 WARNING (MainThread) [homeassistant.components.homekit] HomeKit HASS Bridge cannot add device 60ab2f3fff2f9436acf744ccbbaa550b because it is missing from the device registry
2024-12-20 16:51:25.933 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.0x04cf8cdf3c88e8e8_standby_time: 65535 (range 0.0 - 65534.0)
这是删除组件后的日志，无限重启过程没有日志显示

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.2

**Comment by topsworld** [comment]
您好，无线重启的是ha？

**Comment by symi-daguo** [comment]
是的，ha无线重启，删除插件就正常

**Comment by topsworld** [comment]
> 是的，ha无线重启，删除插件就正常

HA安装方式是docker？
