### ISSUE TITLE
无法执行动作“light/turn_on”   unknown error

### ISSUE THREAD

**Issue by SyengUp** [XiaoMi/ha_xiaomi_home#317]
### Describe the Bug / 描述问题

大部分实体不能控制，报错“ 无法执行动作“light/turn_on” 。 unknown error”。重载集成会恢复正常，1分钟左右后会再次无法控制并报错

### How to Reproduce / 复现步骤

家里停电过后所有设备断电重连重连，之后测试所有light、cover实体都不能控制。

### Expected Behavior / 预期结果

正常控制实体

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.components.websocket_api.http.connection
来源: components/websocket_api/commands.py:245
集成: Home Assistant WebSocket API (文档, 问题)
首次出现: 13:22:37 (8 次总计出现)
上次记录: 13:32:19

[140048095787424] Unexpected exception
[140047951553456] Unexpected exception
[140047951545104] Unexpected exception
[140047953780960] Unexpected exception
[140047939217168] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_lighting/hass_utils.py", line 62, in service_func_proxy
    await existing_service.job.target(call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 265, in async_turn_on
    result = await self.set_property_async(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        prop=self._prop_on, value=value_on)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 573, in set_prop_async
    result: list = await self._http.set_prop_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ])
        ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 749, in set_prop_async
    res_obj = await self.__mihome_api_post_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 317, in __mihome_api_post_async
    http_res = await self._session.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        timeout=timeout)
        ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 607, in _request
    with timer:
         ^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from exc_val
TimeoutError

### Home Assistant Core Version / Home Assistant Core 版本

24.11.0

### Home Assistant Operation System Version / Home Assistant Operation System 版本

13.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

**Comment by iiiilii** [comment]
同样的问题，重载后没一会就回立刻掉线

**Comment by topsworld** [comment]
@SyengUp 您好，停电之前是好使的，然后停电之后就出问题了？

**Comment by topsworld** [comment]
> [iiiilii](/iiiilii)

您好，之前看过一份类似的log，初步定位是网络问题引起的，咱网路都是正常的吧？ 我们尝试压测复现下

**Comment by SyengUp** [comment]
@topsworld 现在不确定和停电没有有关系，也可能和升级v0.1.3有关，昨晚升级了0.1.3没怎么注意，今早刚好停电重连发现的问题

**Comment by iiiilii** [comment]
> > [iiiilii](/iiiilii)
> 
> 您好，之前看过一份类似的log，初步定位是网络问题引起的，咱网路都是正常的吧？ 我们尝试压测复现下

我这边一直没正常过，只有重载的时候正常几秒，后面一直离线。启用了爱快的认证功能，但HA和所有米家设备都已经把MAC添加进了免认证里，HA能正常连外网。。Xiaomi Miot Auto使用一切正常。

**Comment by topsworld** [comment]
> > > [iiiilii](/iiiilii)
> > 
> > 
> > 您好，之前看过一份类似的log，初步定位是网络问题引起的，咱网路都是正常的吧？ 我们尝试压测复现下
> 
> 我这边一直没正常过，只有重载的时候正常几秒，后面一直离线。启用了爱快的认证功能，但HA和所有米家设备都已经把MAC添加进了免认证里，HA能正常连外网。。Xiaomi Miot Auto使用一切正常。

之前同样的问题，我们找云端同事看，是云端给HA发送下行订阅消息，但是HA没有回复，导致云端断开MQTT连接，有尝试试过关闭这个认证功能吗？  miot auto是轮询逻辑，官方集成是订阅逻辑。

**Comment by iiiilii** [comment]
> > > > [iiiilii](/iiiilii)
> > > 
> > > 
> > > 您好，之前看过一份类似的log，初步定位是网络问题引起的，咱网路都是正常的吧？ 我们尝试压测复现下
> > 
> > 
> > 我这边一直没正常过，只有重载的时候正常几秒，后面一直离线。启用了爱快的认证功能，但HA和所有米家设备都已经把MAC添加进了免认证里，HA能正常连外网。。Xiaomi Miot Auto使用一切正常。
> 
> 之前同样的问题，我们找云端同事看，是云端给HA发送下行订阅消息，但是HA没有回复，导致云端断开MQTT连接，有尝试试过关闭这个认证功能吗？ miot auto是轮询逻辑，官方集成是订阅逻辑。

关闭认证后能改善，少部分蓝牙mash设备离线。不过其他通过MQTT连接的设备也都挺正常的。

**Comment by SyengUp** [comment]
@topsworld 我找到原因了，停电路由器重启后openclash启动出现问题导致的，跟集成没关系

**Comment by topsworld** [comment]
如上，用户网络环境问题，问题关闭。

**Comment by iiiilii** [comment]
> 如上，用户网络环境问题，问题关闭。

哥，先别关闭，我的依然没解决。开认证，其他同样需要网络的集成都是正常的（如涂鸦），唯独这个不正常。而且，如果设置静态IP，每改变一次IP地址，都能正常一会，隔十来秒或控制某个设备后立刻离线，但设备是能被控制成功的。我设置过只云端控制，同样是控制成功后立刻离线，能被控制，说明云端访问是OK的。

**Comment by iiiilii** [comment]
@topsworld 我特意写了MQTT程序验证了下，在LINUX设备和ESP32上都能正常。我也用集成的MQTT连接了外网的MQTT服务器，也都正常。以上，至少能说明作为MQTT客户端，开认证不会拦截。

**Comment by iiiilii** [comment]
@topsworld 
![360截图20241221212951](https://github.com/user-attachments/assets/79ddb2cb-196a-4e51-b942-44299feb49b9)

**Comment by topsworld** [comment]
> @topsworld 我特意写了MQTT程序验证了下，在LINUX设备和ESP32上都能正常。我也用集成的MQTT连接了外网的MQTT服务器，也都正常。以上，至少能说明作为MQTT客户端，开认证不会拦截。

你ikuai开的啥认证

**Comment by iiiilii** [comment]
> > @topsworld 我特意写了MQTT程序验证了下，在LINUX设备和ESP32上都能正常。我也用集成的MQTT连接了外网的MQTT服务器，也都正常。以上，至少能说明作为MQTT客户端，开认证不会拦截。
> 
> 你ikuai开的啥认证

WEB认证

**Comment by topsworld** [comment]
> > > @topsworld 我特意写了MQTT程序验证了下，在LINUX设备和ESP32上都能正常。我也用集成的MQTT连接了外网的MQTT服务器，也都正常。以上，至少能说明作为MQTT客户端，开认证不会拦截。
> > 
> > 
> > 你ikuai开的啥认证
> 
> WEB认证

哪个配置页面

**Comment by iiiilii** [comment]
> > > > @topsworld 我特意写了MQTT程序验证了下，在LINUX设备和ESP32上都能正常。我也用集成的MQTT连接了外网的MQTT服务器，也都正常。以上，至少能说明作为MQTT客户端，开认证不会拦截。
> > > 
> > > 
> > > 你ikuai开的啥认证
> > 
> > 
> > WEB认证
> 
> 哪个配置页面

![360截图20241221213530919](https://github.com/user-attachments/assets/ec1b890e-ce8b-4e4d-b528-ffc676837410)

**Comment by iiiilii** [comment]
![2](https://github.com/user-attachments/assets/5d6b0508-d041-4f65-886d-96883aa14882)

**Comment by iiiilii** [comment]
@topsworld 我猜测可能是域名解析出了问题，于是手动改了DNS，已经稳定到现在不掉线了。能否确认是这个问题可能还要具体分析。
