### ISSUE TITLE
Token 自动刷新失败

### ISSUE THREAD

**Issue by ZnDong** [XiaoMi/ha_xiaomi_home#383]
### Describe the Bug / 描述问题

由于自动刷新Token失败，导致存储在本地的Token过期，进而无法控制设备，但能收到设备开关的HA日志。

### How to Reproduce / 复现步骤

2024-12-23 12:07:12 控制设备失败，但能收到设备开/关的日志。同时米家集成发出“账号过期”的HA通知
2024-12-23 12:37 手动完成Oatuh授权，设备恢复控制

### Expected Behavior / 预期结果

成功自动刷新Token

### Home Assistant Logs / 系统日志

```python
2024-12-21 20:43:54.598 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['**********|2|5']
2024-12-22 07:42:30.770 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh oauth info error (**********, cn), 'MIoTOauthClient' object has no attribute '_get_token_async', Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 449, in refresh_oauth_info_async
    valid_auth_info = await self._oauth.refresh_access_token_async(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        refresh_token=auth_info['refresh_token'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 207, in refresh_access_token_async
    return await self._get_token_async(data={
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MIoTOauthClient' object has no attribute '_get_token_async'

2024-12-23 12:07:12.436 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 430, in post
    response = await shield(
               ^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 97, in async_turn_on
    await self.set_property_async(value=True)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 573, in set_prop_async
    result: list = await self._http.set_prop_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ])
        ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 750, in set_prop_async
    res_obj = await self.__mihome_api_post_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 323, in __mihome_api_post_async
    raise MIoTHttpError(
        'mihome api get failed, unauthorized(401)',
        MIoTErrorCode.CODE_HTTP_INVALID_ACCESS_TOKEN)
custom_components.xiaomi_home.miot.miot_error.MIoTHttpError: mihome api get failed, unauthorized(401)
2024-12-23 12:07:57.643 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 430, in post
    response = await shield(
               ^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 97, in async_turn_on
    await self.set_property_async(value=True)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 573, in set_prop_async
    result: list = await self._http.set_prop_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ])
        ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 750, in set_prop_async
    res_obj = await self.__mihome_api_post_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 323, in __mihome_api_post_async
    raise MIoTHttpError(
        'mihome api get failed, unauthorized(401)',
        MIoTErrorCode.CODE_HTTP_INVALID_ACCESS_TOKEN)
custom_components.xiaomi_home.miot.miot_error.MIoTHttpError: mihome api get failed, unauthorized(401)
2024-12-23 12:09:00.409 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [**********] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 639, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/xiaomi_home/light.py", line 299, in async_turn_off
    return await self.set_property_async(prop=self._prop_on, value=value_on)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 867, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=prop.service.iid,
        piid=prop.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 573, in set_prop_async
    result: list = await self._http.set_prop_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ])
        ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 750, in set_prop_async
    res_obj = await self.__mihome_api_post_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 323, in __mihome_api_post_async
    raise MIoTHttpError(
        'mihome api get failed, unauthorized(401)',
        MIoTErrorCode.CODE_HTTP_INVALID_ACCESS_TOKEN)
custom_components.xiaomi_home.miot.miot_error.MIoTHttpError: mihome api get failed, unauthorized(401)
2024-12-23 12:09:16.743 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 430, in post
    response = await shield(
               ^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 97, in async_turn_on
    await self.set_property_async(value=True)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 573, in set_prop_async
    result: list = await self._http.set_prop_async(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ])
        ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 750, in set_prop_async
    res_obj = await self.__mihome_api_post_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 323, in __mihome_api_post_async
    raise MIoTHttpError(
        'mihome api get failed, unauthorized(401)',
        MIoTErrorCode.CODE_HTTP_INVALID_ACCESS_TOKEN)
custom_components.xiaomi_home.miot.miot_error.MIoTHttpError: mihome api get failed, unauthorized(401)
2024-12-23 12:36:51.506 ERROR (ha.**********) [custom_components.xiaomi_home.miot.miot_client] ha.**********, mips disconnect, 0, None
2024-12-23 12:36:51.588 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh oauth info error (**********, cn), 'MIoTOauthClient' object has no attribute '_get_token_async', Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 449, in refresh_oauth_info_async
    valid_auth_info = await self._oauth.refresh_access_token_async(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        refresh_token=auth_info['refresh_token'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 207, in refresh_access_token_async
    return await self._get_token_async(data={
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MIoTOauthClient' object has no attribute '_get_token_async'

2024-12-23 12:36:55.599 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh oauth info error (**********, cn), 'MIoTOauthClient' object has no attribute '_get_token_async', Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 449, in refresh_oauth_info_async
    valid_auth_info = await self._oauth.refresh_access_token_async(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        refresh_token=auth_info['refresh_token'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 207, in refresh_access_token_async
    return await self._get_token_async(data={
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MIoTOauthClient' object has no attribute '_get_token_async'

2024-12-23 12:37:16.260 WARNING (MainThread) [py.warnings] /config/custom_components/xiaomi_home/miot/miot_cloud.py:256: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self._session.close()

2024-12-23 12:37:16.261 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session (None)
2024-12-23 12:37:16.263 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector (None)
2024-12-23 12:38:07.951 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['**********|2|5']
```

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

null

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

已对日志中的时间进行随机偏移，账号信息替换为**********

**Comment by topsworld** [comment]
@ZnDong  问题在v0.1.4B0已修复
