### ISSUE TITLE
集成提示设置失败检查日志

### ISSUE THREAD

**Issue by Apcan** [XiaoMi/ha_xiaomi_home#385]
### Describe the Bug / 描述问题

最新版本，按步骤集成，集成后提示设置失败

### How to Reproduce / 复现步骤

授权后选择其中一个家庭，选择同步房间，不排除非标准实体，集成后提示失败
![image](https://github.com/user-attachments/assets/c9703deb-31ef-4c21-97c7-0d23cf3fe2b0)

### Expected Behavior / 预期结果

能集成展示设备

### Home Assistant Logs / 系统日志

2024-12-23 14:13:27.021 ERROR (MainThread) [homeassistant.components.homekit] HomeKit   Play Control cannot startup: entity not available: {'include_domains': [], 'include_entities': ['media_player.xiaomi_rmh1_c6b3_play_control'], 'exclude_domains': [], 'exclude_entities': [], 'include_entity_globs': [], 'exclude_entity_globs': []}
2024-12-23 14:13:27.083 ERROR (MainThread) [homeassistant.components.homekit] HomeKit Xiaomi Smart Camera C400 Camera Control cannot startup: entity not available: {'include_domains': [], 'include_entities': ['camera.chuangmi_039a01_d6cc_camera_control'], 'exclude_domains': [], 'exclude_entities': [], 'include_entity_globs': [], 'exclude_entity_globs': []}
2024-12-23 14:14:47.486 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'lumi.158d000926dbd9', 'uid': 109768121, 'token': '', 'name': 'Aqara魔方控制器', 'pid': 3, 'mac': '', 'ssid': 'hs-free-1', 'bssid': '34:8A:12:49:7F:34', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '499270924', 'show_mode': 1, 'model': 'lumi.sensor_cube.aqgl01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.0.0_0005', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1683786962, 'freqFlag': True, 'hide_mode': 0, 'cnt': 3, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:14:47.490 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'huami.39874/AAAAC12WR47548', 'uid': 109768121, 'token': '', 'name': '小米手环7 NFC版', 'pid': 6, 'mac': 'D4:4A:46:40:03:88', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'show_mode': 1, 'model': 'hmpace.watch.v7nfc', 'permitLevel': 16, 'isOnline': False, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1706092286, 'freqFlag': True, 'hide_mode': 0, 'cnt': 6, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:14:47.515 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'ir.1831712513831079936', 'uid': 109768121, 'token': '', 'name': '空调', 'pid': 15, 'mac': '', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '636804035', 'show_mode': 1, 'model': 'miir.remote.ir01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1725549269, 'freqFlag': True, 'hide_mode': 0, 'cnt': 15, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:14:47.541 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'ir.1833155147891888128', 'uid': 109768121, 'token': '', 'name': '音响', 'pid': 15, 'mac': '', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '636804035', 'show_mode': 1, 'model': 'miir.remote.ir01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1725893220, 'freqFlag': True, 'hide_mode': 0, 'cnt': 15, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:14:47.580 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, huami.39874/AAAAC12WR47548
2024-12-23 14:14:47.582 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, ir.1831712513831079936
2024-12-23 14:14:47.583 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, ir.1833155147891888128
2024-12-23 14:14:47.583 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, lumi.158d000926dbd9
2024-12-23 14:15:19.573 WARNING (MainThread) [py.warnings] /config/custom_components/xiaomi_home/miot/miot_client.py:1072: RuntimeWarning: coroutine 'MIoTClient.__on_lan_device_state_changed' was never awaited
  self.__on_lan_device_state_changed(

2024-12-23 14:15:20.272 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 苹果: 109768121 [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
    unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'
2024-12-23 14:15:21.283 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'ir.1833155147891888128', 'uid': 109768121, 'token': '', 'name': '音响', 'pid': 15, 'mac': '', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '636804035', 'show_mode': 1, 'model': 'miir.remote.ir01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1725893220, 'freqFlag': True, 'hide_mode': 0, 'cnt': 15, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:15:21.285 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'huami.39874/AAAAC12WR47548', 'uid': 109768121, 'token': '', 'name': '小米手环7 NFC版', 'pid': 6, 'mac': 'D4:4A:46:40:03:88', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'show_mode': 1, 'model': 'hmpace.watch.v7nfc', 'permitLevel': 16, 'isOnline': False, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1706092286, 'freqFlag': True, 'hide_mode': 0, 'cnt': 6, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:15:21.286 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'ir.1831712513831079936', 'uid': 109768121, 'token': '', 'name': '空调', 'pid': 15, 'mac': '', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'parent_id': '636804035', 'show_mode': 1, 'model': 'miir.remote.ir01', 'permitLevel': 16, 'isOnline': True, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1725549269, 'freqFlag': True, 'hide_mode': 0, 'cnt': 15, 'comFlag': 129, 'carPicInfo': ''}
2024-12-23 14:15:21.307 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, huami.39874/AAAAC12WR47548
2024-12-23 14:15:21.309 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, ir.1831712513831079936
2024-12-23 14:15:21.309 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, ir.1833155147891888128
2024-12-23 14:15:38.991 INFO (MainThread) [custom_components.xiaomi_home.miot.miot_client] instance exist, 01JFS2FQMSVTAY9WZW0TBX0MRM
2024-12-23 14:15:39.170 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_spec] use local spec std cache, ts->1734933567
2024-12-23 14:15:39.526 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_storage] load manufacturer data success
2024-12-23 14:15:39.536 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_spec] get from cache, urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx05:1
2024-12-23 14:15:39.538 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_client] client sub device state, 265671035
2024-12-23 14:15:39.538 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_device] miot device init {'home_id': '274001009696', 'home_name': '苹果的家庭', 'room_id': '274001009696', 'room_name': '苹果的家庭', 'group_id': 'ae2988e984dcba1e', 'did': '265671035', 'uid': 109768121, 'name': '小爱音箱Play（2019款）', 'urn': 'urn:miot-spec-v2:device:speaker:0000A015:xiaomi-lx05:1', 'model': 'xiaomi.wifispeaker.lx05', 'connect_type': 0, 'token': '6164664638414c545270617242463038', 'online': True, 'icon': None, 'parent_id': None, 'manufacturer': '小米', 'voice_ctrl': 2, 'rssi': -57, 'owner': None, 'pid': 0, 'local_ip': None, 'ssid': 'APCAN-TP', 'bssid': '18:F2:2C:AC:B1:FE', 'order_time': 1719839776, 'fw_version': '1.82.10', 'mcu_version': None, 'platform': None}
2024-12-23 14:15:39.539 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 苹果: *** [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
    unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core Version / Home Assistant Core 版本

2024.9.1

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20240906.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

**Comment by HythemK** [comment]
我也是这样，有解决办法吗

**Comment by zghnwsq** [comment]
升级下ha版本
