### ISSUE TITLE
小米触屏音箱(xiaomi.wifispeaker.lx04)无法播放文本

### ISSUE THREAD

**Issue by whzzone** [XiaoMi/ha_xiaomi_home#393]
### Describe the Bug / 描述问题

如题，小米触屏音箱(xiaomi.wifispeaker.lx04)无法播放文本

### How to Reproduce / 复现步骤

![image](https://github.com/user-attachments/assets/a1a6e0dd-6f7c-47ff-a55f-205ac040e9cd)
输入文本后回车

### Expected Behavior / 预期结果

播放出文本

### Home Assistant Logs / 系统日志

2024-12-23 13:16:34.409 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547784789008] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_100174256_lx04_play_text_a_5_1), invalid action params format, 你好
2024-12-23 13:18:24.050 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 播放文本(text.xiaomi_cn_100174256_lx04_play_text_a_5_1), invalid action params format, 大家好
2024-12-23 13:18:24.051 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547784789008] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_100174256_lx04_play_text_a_5_1), invalid action params format, 大家好


### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

2024.12.5

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b0

### Additional Context / 其他说明

无

**Comment by topsworld** [comment]
您好，可以去discussion查看使用方法，或者readme，官方集成中：
可以加个大括号：  ["大家好"]
