### ISSUE TITLE
登录后没有任何设备显示

### ISSUE THREAD

**Issue by uestcwangci** [XiaoMi/ha_xiaomi_home#427]
### Describe the Bug / 描述问题

报错没有设备或实体

### How to Reproduce / 复现步骤

同上

### Expected Behavior / 预期结果

我有7个设备

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.config_entries
来源: config_entries.py:604
首次出现: 20:45:57 (8 次总计出现)
上次记录: 21:01:05

Error setting up entry 王超: 42595701 [中国大陆] for xiaomi_home
Error setting up entry WongChad: 42595701 [中国大陆] for xiaomi_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
    raise err
  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
    device.spec_transform()
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
    prop.external_unit = self.unit_convert(prop.unit)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
    unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core Version / Home Assistant Core 版本

2024.9.3

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20240909.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by topsworld** [comment]
已修复，可以试试稍后发布的0.1.4Bb1版本
