### ISSUE TITLE
小爱音箱无法执行文本命令

### ISSUE THREAD

**Issue by feidian8352** [XiaoMi/ha_xiaomi_home#435]
### Describe the Bug / 描述问题

小爱音箱无法执行文本命令

### How to Reproduce / 复现步骤

在小爱音箱中执行播放文本中输入你好或者["你好"]，都 不能执行
![image](https://github.com/user-attachments/assets/54c00770-a0b6-41f6-85f3-ebdf48ba6580)

### Expected Behavior / 预期结果

改进， 原来的用的其它插件都很好的执行

### Home Assistant Logs / 系统日志

2024-12-25 08:44:36.777 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bemfa which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.783 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kadermanager which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.793 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration qweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.800 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.804 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration colorfulclouds which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.810 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:36.817 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-25 08:44:58.913 WARNING (ImportExecutor_0) [homeassistant.backports.enum] StrEnum was used from bemfa, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'bemfa' custom integration
2024-12-25 08:44:59.036 WARNING (ImportExecutor_0) [homeassistant.components.camera] STATE_IDLE was used from bemfa, this is a deprecated constant which will be removed in HA Core 2025.10. Use CameraState.IDLE instead, please report it to the author of the 'bemfa' custom integration
2024-12-25 08:44:59.064 WARNING (ImportExecutor_0) [homeassistant.components.camera] STATE_IDLE was used from bemfa, this is a deprecated constant which will be removed in HA Core 2025.10. Use CameraState.IDLE instead, please report it to the author of the 'bemfa' custom integration
2024-12-25 08:44:59.175 WARNING (ImportExecutor_0) [homeassistant.const] STATE_LOCKED was used from bemfa, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'bemfa' custom integration
2024-12-25 08:45:00.504 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend_experimental", False)])` at custom_components/hacs/frontend.py, line 37: hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
2024-12-25 08:45:00.531 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])` at custom_components/hacs/frontend.py, line 45: hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
2024-12-25 08:45:00.576 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend, which should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 58: hass.components.frontend.async_register_built_in_panel(. This will stop working in Home Assistant 2025.3, please create a bug report at https://github.com/hacs/integration/issues
2024-12-25 08:45:00.599 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])` at custom_components/hacs/base.py, line 1212: self.hass.http.register_static_path(. This will stop working in Home Assistant 2025.7, please create a bug report at https://github.com/hacs/integration/issues
2024-12-25 08:45:05.323 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-25 08:45:05.328 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-25 08:45:05.346 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-25 08:45:05.354 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-25 08:45:05.357 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-12-25 08:45:08.928 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for espswitch01 @ 192.168.5.192: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.5.192', port=6053))]: [Errno 113] Connect call failed ('192.168.5.192', 6053) (SocketAPIError)
2024-12-25 08:45:20.632 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event, which should be updated to import functions used from event directly at custom_components/hacs/base.py, line 636: self.hass.helpers.event.async_track_time_interval(. This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/hacs/integration/issues
2024-12-25 08:46:05.836 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for esp @ 192.168.1.19: Timeout while connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.1.19', port=6053))] (TimeoutAPIError)
2024-12-25 08:58:58.101 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid action params format, ["今天的天气怎么样“]
2024-12-25 08:58:58.103 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 360, in raw_decode
    obj, end = self.scan_once(s, idx)
               ~~~~~~~~~~~~~~^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid action params format, ["今天的天气怎么样“]
2024-12-25 08:59:10.201 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid action params format, 今天的天气怎么样
2024-12-25 08:59:10.202 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid action params format, 今天的天气怎么样
2024-12-25 09:00:11.933 ERROR (MainThread) [root] action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid params item, which item(指令静默执行) in the list must be int, ["天气怎么样",false]
2024-12-25 09:00:11.934 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 146, in async_set_value
    raise ValueError(
    ...<2 lines>...
        f' in the list must be {prop.format_}, {value}')
ValueError: action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid params item, which item(指令静默执行) in the list must be int, ["天气怎么样",false]
2024-12-25 09:01:53.905 ERROR (MainThread) [root] action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid params item, which item(指令静默执行) in the list must be int, ["天气预报",false]
2024-12-25 09:01:53.906 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 146, in async_set_value
    raise ValueError(
    ...<2 lines>...
        f' in the list must be {prop.format_}, {value}')
ValueError: action exec failed,  智能音箱 执行文本指令(text.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid params item, which item(指令静默执行) in the list must be int, ["天气预报",false]
2024-12-25 09:03:27.823 ERROR (MainThread) [custom_components.xiaomi_home.notify] action exec failed,  智能音箱 执行文本指令(notify.xiaomi_cn_289448190_l7a_execute_text_directive_a_5_5), invalid action params, ["电脑已关机"]
2024-12-25 09:05:05.869 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, ["你好”]
2024-12-25 09:05:05.870 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 360, in raw_decode
    obj, end = self.scan_once(s, idx)
               ~~~~~~~~~~~~~~^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, ["你好”]
2024-12-25 09:05:36.257 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你好
2024-12-25 09:05:36.258 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382869942432] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你好
2024-12-25 09:28:10.723 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你好
2024-12-25 09:28:10.725 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382853774736] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你好
2024-12-25 09:28:35.138 ERROR (MainThread) [custom_components.xiaomi_home.text] action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你
2024-12-25 09:28:35.139 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140382853774736] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/text.py", line 124, in async_set_value
    in_list = json.loads(value)
  File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 129, in async_set_value
    raise ValueError(
        f'action exec failed, {self.name}({self.entity_id}), '
        f'invalid action params format, {value}') from e
ValueError: action exec failed,  智能音箱 播放文本(text.xiaomi_cn_289448190_l7a_play_text_a_5_1), invalid action params format, 你


### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

### Additional Context / 其他说明

_No response_

**Comment by topsworld** [comment]
您好，非问题，请仔细阅读readme，设备action操作对格式有要求。
