### ISSUE TITLE
[Bug]: 登录报错

### ISSUE THREAD

**Issue by Chanli520** [XiaoMi/ha_xiaomi_home#48]
### Describe the bug / 描述问题

登录报错

### To Reproduce / 复现步骤

配置完成后 失败

### Expected behavior / 预期结果

登录成功

### Home Assistant Logs / 系统日志

2024-12-17 09:57:19.700 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Eric: 144620767 [中国大陆] for xiaomi_home

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup

    result = await component.async_setup_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry

    raise err

  File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry

    device.spec_transform()

  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 525, in spec_transform

    device_entity = self.parse_miot_device_entity(

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 433, in parse_miot_device_entity

    prop.external_unit = self.unit_convert(prop.unit)

                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 619, in unit_convert

    'μS/cm': UnitOfConductivity.MICROSIEMENS_PER_CM,

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### Home Assistant Core version / Home Assistant Core 版本

2024.11.0

### Home Assistant Operation System version / Home Assistant Operation System 版本

13.0

### Xiaomi Home integration version / 米家集成版本

v.0.1

### Additional context / 其他说明

登录报错

**Comment by topsworld** [comment]
您好，集成需要core版本2024.11.0及以上
