### ISSUE TITLE
xiaomi.wifispeaker.l05g does not work

### ISSUE THREAD

**Issue by azeos** [XiaoMi/ha_xiaomi_home#491]
### Describe the Bug / 描述问题

The smart speaker does not respond to any command

### How to Reproduce / 复现步骤

![imagen](https://github.com/user-attachments/assets/70ebcce4-744f-4ac8-845e-2fab0d8ae961)
![imagen](https://github.com/user-attachments/assets/463738ac-66fc-4de3-a8a9-ae10c80c1c14)

### Expected Behavior / 预期结果

Command should respond correctly

### Reproduce Time / 问题复现的时间点

2024-12-28 21:11

### Home Assistant Logs / 系统日志

2024-12-28 21:21:54.608 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-28 21:21:54.629 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-28 21:22:22.615 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/custom_components/xiaomi_home/miot/lan/profile_models.yaml', 'r') inside the event loop by custom integration 'xiaomi_home' at custom_components/xiaomi_home/miot/common.py, line 78: with open(yaml_file, 'r', encoding='utf-8') as f: (offender: /config/custom_components/xiaomi_home/miot/common.py, line 78: with open(yaml_file, 'r', encoding='utf-8') as f:), please create a bug report at https://github.com/XiaoMi/ha_xiaomi_home/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xiaomi_home/__init__.py", line 108, in async_setup_entry
    miot_client: MIoTClient = await get_miot_instance_async(
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 1837, in get_miot_instance_async
    await miot_client.init_async()
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 277, in init_async
    await self._miot_lan.vote_for_lan_ctrl_async(
  File "/config/custom_components/xiaomi_home/miot/miot_lan.py", line 682, in vote_for_lan_ctrl_async
    await self.init_async()
  File "/config/custom_components/xiaomi_home/miot/miot_lan.py", line 606, in init_async
    self._profile_models = load_yaml_file(
  File "/config/custom_components/xiaomi_home/miot/common.py", line 78, in load_yaml_file
    with open(yaml_file, 'r', encoding='utf-8') as f:

2024-12-28 21:22:32.575 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_client] refresh props failed, cloud, ['561259112|2|1', '561259112|6|4', '561259112|3|3', '561259112|3|1', '561259112|6|2', '561259112|6|3', '561259112|2|2', '561259112|4|1', '561259112|6|1']
2024-12-28 21:23:58.482 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1791759456] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 591, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: Error de ejecución, Error de valor de propiedad

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/xiaomi_home/number.py", line 106, in async_set_native_value
    await self.set_property_async(value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: Error de ejecución, Error de valor de propiedad, number.xiaomi_us_561259112_l05g_volume_p_2_1,  Speaker Volume

2024-12-28 21:27:03.729 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] mihome api post, https://us.ha.api.io.mi.com/app/v2/miotspec/prop/set, {'params': [{'did': '561259112', 'siid': 2, 'piid': 1, 'value': 61}]} -> {'code': 0, 'message': 'ok', 'result': [{'did': '561259112', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'code': -704220043, 'exe_time': 0}]}
2024-12-28 21:27:03.730 DEBUG (MainThread) [custom_components.xiaomi_home.miot.miot_client] set prop response, 561259112.2.1, 61, result, [{'did': '561259112', 'iid': '0.2.1', 'siid': 2, 'piid': 1, 'code': -704220043, 'exe_time': 0}]
2024-12-28 21:27:03.731 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1791759456] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 591, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: Error de ejecución, Error de valor de propiedad

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 122, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/xiaomi_home/number.py", line 106, in async_set_native_value
    await self.set_property_async(value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: Error de ejecución, Error de valor de propiedad, number.xiaomi_us_561259112_l05g_volume_p_2_1,  Speaker Volume

### Log Timezone / 日志时区

America/Argentina/Buenos Aires

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.1

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

The devices is detected at the installation, but once it's installed no command works.
I can use the device from my Google Home app. From the "Mi Home app" I can only use the IR, I can't control the volume or other options.

**Comment by SusanPhevos** [comment]
May you try v0.2.1? Does the problem still exist?

**Comment by azeos** [comment]
Still the same problem. I re added the device but I'm getting the same results.

**Comment by SusanPhevos** [comment]
Due to privacy regulations, engineers in Mainland China do not have the authority to view messages and cloud logs of devices in other regions, and therefore are unable to troubleshoot this issue. Sorry.
