### ISSUE TITLE
获取登录授权信息（OAuth token）失败。

### ISSUE THREAD

**Issue by RCLiLong** [XiaoMi/ha_xiaomi_home#495]
### Describe the Bug / 描述问题

授权失败 已经尝试过多次，试过chrome（131.0.6778.205）与edge（131.0.2903.112）。ha域名已经添加到host中

### How to Reproduce / 复现步骤

再次登录即可复现

### Expected Behavior / 预期结果

登录失败

### Reproduce Time / 问题复现的时间点

2024-12-29 18:55

### Home Assistant Logs / 系统日志

2024-12-29 18:45:47.088 ERROR (MainThread) [custom_components.xiaomi_home.config_flow] get_access_token, Cannot connect to host ha.api.io.mi.com:443 ssl:default [Could not contact DNS servers], Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/resolver.py", line 103, in resolve
    resp = await self._resolver.getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
aiodns.error.DNSError: (11, 'Could not contact DNS servers')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1351, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 995, in _resolve_host
    return await asyncio.shield(resolved_host_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1026, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/resolver.py", line 112, in resolve
    raise OSError(None, msg) from exc
OSError: [Errno None] Could not contact DNS servers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/config_flow.py", line 337, in __check_oauth_async
    auth_info = await self._miot_oauth.get_access_token_async(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        code=oauth_code)
        ^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 189, in get_access_token_async
    return await self.__get_token_async(data={
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    })
    ^^
  File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 145, in __get_token_async
    http_res = await self._session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1357, in _create_direct_connection
    raise ClientConnectorDNSError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [Could not contact DNS servers]

2024-12-29 18:45:47.089 ERROR (MainThread) [custom_components.xiaomi_home.config_flow] task_oauth exception, get_token_error

补充信息
container内
cat /etc/resolv.conf
‘#’ Generated by Docker Engine.
‘#’ This file can be edited; Docker Engine will not make further changes once it
‘#’ has been modified.

nameserver fe80::1%wlan0

‘#’ Based on host file: '/etc/resolv.conf'
'#' Overrides: []

nslookup ha.api.io.mi.com
Server:         fe80::1%3%3
Address:        fe80::1%3#53

Non-authoritative answer:
Name:   ha.api.io.mi.com
Address: 111.202.1.140
Name:   ha.api.io.mi.com
Address: 120.52.181.54
Name:   ha.api.io.mi.com
Address: 111.206.174.241

### Log Timezone / 日志时区

Asic/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3 v0.1.4b0 v0.1.4b1 都试过了

### Additional Context / 其他说明

服务器设备是arm结构的

**Comment by topsworld** [comment]
aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [Could not contact DNS servers]
看日志，ha的dns解析存在问题，建议检查下网络配置。

**Comment by topsworld** [comment]
> aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [Could not contact DNS servers] 看日志，ha的dns解析存在问题，建议检查下网络配置。

问题属于ha无法正确解析ha.api.io.mi.com这个地址

**Comment by RCLiLong** [comment]
> > aiohttp.client_exceptions.ClientConnectorDNSError: Cannot connect to host ha.api.io.mi.com:443 ssl:default [Could not contact DNS servers] 看日志，ha的dns解析存在问题，建议检查下网络配置。
> 
> 问题属于ha无法正确解析ha.api.io.mi.com这个地址

确实是这个原因，感谢
设备是arm架构，ubuntu系统。
默认的dns为resolvconf.service，bash可以这么使用，不过看日志，ha的程序好像使用不了resolvconf.service
处理方法，将resolvconf.service停掉
```
systemctl stop resolvconf.service 
systemctl disable resolvconf.service 
```

将原来处于resolvconf.service后端的dns添加到/etc/resolv.conf文件中
cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 114.114.114.114

重启 ha的容器，检查dns配置文件
cat /etc/resolv.conf 
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 8.8.8.8
nameserver 114.114.114.114

# Based on host file: '/etc/resolv.conf'
# Overrides: []

这样子就可以正常认证了。

**Comment by topsworld** [comment]
如上，非问题
