### ISSUE TITLE
经常出现oauth认证失效，需要重新登陆账号认证的问题

### ISSUE THREAD

**Issue by iceveil** [XiaoMi/ha_xiaomi_home#496]
### Describe the Bug / 描述问题

经常出现oauth认证失效，需要重新登陆账号认证的问题

### How to Reproduce / 复现步骤

没有固定复现步骤，正常运行一两天或三四天时间就会出现一次

### Expected Behavior / 预期结果

正常

### Reproduce Time / 问题复现的时间点

2024-12-29

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

14.0

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

**Comment by NXY666** [comment]
是的，这个问题也困扰着我。

我的集成版本是0.1.4b1。

**Comment by sunshinenny** [comment]
+1 (V0.13)

**Comment by coolqoo** [comment]
+1 v0.1.3

**Comment by unijiang** [comment]
每隔几天反复出现

**Comment by qiyell** [comment]
对，太频繁的掉了，这点非常影响使用感受啊，不知道啥时候就不能控制了。。。。我现在都又用回Xiaomi Miot Auto，希望能尽快解决，我还是非常希望用上官方的，更全面一些

**Comment by topsworld** [comment]
您好，可以尝试下预发布版本v0.1.4b1

**Comment by NXY666** [comment]
> 您好，可以尝试下预发布版本v0.1.4b1

我目前使用的就是v0.1.4b1，但是情况并不乐观。

我看到有token刷新失败的报错日志。

```
此错误来自自定义集成。

日志记录器: custom_components.xiaomi_home.miot.miot_client
来源: custom_components/xiaomi_home/miot/miot_client.py:547
集成: Xiaomi Home (文档, 问题)
首次出现: 22:24:27 (2 次总计出现)
上次记录: 22:24:43

refresh oauth info error (***, cn), invalid http response, <bound method ClientResponse.text of <ClientResponse(https://ha.api.io.mi.com/app/v2/ha/oauth/get_token?data=%7B%22client_id%22:+***,+%22redirect_uri%22:+%22http://homeassistant.local:8123/api/webhook/***%22,+%22refresh_token%22:+%22***%22%7D) [200 OK]> <CIMultiDictProxy('Server': 'Tengine', 'Date': 'Sun, 29 Dec 2024 14:24:27 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '252', 'Connection': 'keep-alive', 'Request-Id': '***', 'X-Xiaomi-Status-Code': '400')> >, Traceback (most recent call last): File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 516, in refresh_oauth_info_async valid_auth_info = await self._oauth.refresh_access_token_async( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ refresh_token=auth_info['refresh_token']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 208, in refresh_access_token_async return await self.__get_token_async(data={ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<3 lines>... }) ^^ File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 169, in __get_token_async raise MIoTOauthError(f'invalid http response, {http_res.text}') custom_components.xiaomi_home.miot.miot_error.MIoTOauthError: invalid http response, <bound method ClientResponse.text of <ClientResponse(https://ha.api.io.mi.com/app/v2/ha/oauth/get_token?data=%7B%22client_id%22:+***,+%22redirect_uri%22:+%22http://homeassistant.local:8123/api/webhook/***%22,+%22refresh_token%22:+%22***%22%7D) [200 OK]> <CIMultiDictProxy('Server': 'Tengine', 'Date': 'Sun, 29 Dec 2024 14:24:27 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '252', 'Connection': 'keep-alive', 'Request-Id': '***', 'X-Xiaomi-Status-Code': '400')> >
```

**Comment by lsl9119** [comment]
用同样的问题，而且必须连回本地来验证登录，还不能内网穿透后反向代理回来操作。

**Comment by memory8464** [comment]
+1 v0.1.3

**Comment by topsworld** [comment]
> > 您好，可以尝试下预发布版本v0.1.4b1
> 
> 我目前使用的就是v0.1.4b1，但是情况并不乐观。
> 
> 我看到有token刷新失败的报错日志。
> 
> ```
> 此错误来自自定义集成。
> 
> 日志记录器: custom_components.xiaomi_home.miot.miot_client
> 来源: custom_components/xiaomi_home/miot/miot_client.py:547
> 集成: Xiaomi Home (文档, 问题)
> 首次出现: 22:24:27 (2 次总计出现)
> 上次记录: 22:24:43
> 
> refresh oauth info error (***, cn), invalid http response, <bound method ClientResponse.text of <ClientResponse(https://ha.api.io.mi.com/app/v2/ha/oauth/get_token?data=%7B%22client_id%22:+***,+%22redirect_uri%22:+%22http://homeassistant.local:8123/api/webhook/***%22,+%22refresh_token%22:+%22***%22%7D) [200 OK]> <CIMultiDictProxy('Server': 'Tengine', 'Date': 'Sun, 29 Dec 2024 14:24:27 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '252', 'Connection': 'keep-alive', 'Request-Id': '***', 'X-Xiaomi-Status-Code': '400')> >, Traceback (most recent call last): File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 516, in refresh_oauth_info_async valid_auth_info = await self._oauth.refresh_access_token_async( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ refresh_token=auth_info['refresh_token']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 208, in refresh_access_token_async return await self.__get_token_async(data={ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<3 lines>... }) ^^ File "/config/custom_components/xiaomi_home/miot/miot_cloud.py", line 169, in __get_token_async raise MIoTOauthError(f'invalid http response, {http_res.text}') custom_components.xiaomi_home.miot.miot_error.MIoTOauthError: invalid http response, <bound method ClientResponse.text of <ClientResponse(https://ha.api.io.mi.com/app/v2/ha/oauth/get_token?data=%7B%22client_id%22:+***,+%22redirect_uri%22:+%22http://homeassistant.local:8123/api/webhook/***%22,+%22refresh_token%22:+%22***%22%7D) [200 OK]> <CIMultiDictProxy('Server': 'Tengine', 'Date': 'Sun, 29 Dec 2024 14:24:27 GMT', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '252', 'Connection': 'keep-alive', 'Request-Id': '***', 'X-Xiaomi-Status-Code': '400')> >
> ```

咱这个账号在几台ha上登录了？

**Comment by NXY666** [comment]
> 咱这个账号在几台ha上登录了？

两台，另一台用的0.1.3似乎不会掉线，就这一台不管用什么都会掉 :(

**Comment by topsworld** [comment]
> > 咱这个账号在几台ha上登录了？
> 
> 两台，另一台用的0.1.3似乎不会掉线，就这一台不管用什么都会掉 :(

这是一个已知问题，同账号多ha登录会导致token刷新失效，只有一台能正常刷新token，近期会解决这个问题

**Comment by iceveil** [comment]
我的情况是只有一台ha登陆，还是会失效的，同时使用的还有xiaomi miot auto，不知道会不会有影响

**Comment by Jumeng-ms** [comment]
> 我的情况是只有一台ha登陆，还是会失效的，同时使用的还有xiaomi miot auto，不知道会不会有影响

我也是一台HA登录， xiaomi miot auto已经删除了 还是经常掉线失效

**Comment by uduoy** [comment]
我有这个问题，把一个家庭的设备转移到另一个帐号貌似好点了

**Comment by Maotechh** [comment]
我只有一台登陆，但经常失效
<img width="480" alt="截屏2024-12-31 10 56 17" src="https://github.com/user-attachments/assets/a31747d7-e9c6-4064-9dff-8c5190aac9ab" />

**Comment by zwlhome** [comment]
> 我只有一台登陆，但经常运行 <img alt="截屏2024-12-31 10 56 17" width="480" src="https://private-user-images.githubusercontent.com/109655023/399399460-a31747d7-e9c6-4064-9dff-8c5190aac9ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDgxOTgsIm5iZiI6MTczNTY0Nzg5OCwicGF0aCI6Ii8xMDk2NTUwMjMvMzk5Mzk5NDYwLWEzMTc0N2Q3LWU5YzYtNDA2NC05ZGZmLThjNTE5MGFhYzlhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMjI0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTJiZTdiYjYxZTVlYTAzOTU4ZTBiNGRiY2YxNGZhM2ViYWZhMzBhNDg2OTIwYjJmZjk0NjA0YjZiMGZkNzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j-3EnU7K2vD0SFB1s1n5hY5qQWb-slgucEWilZ5batQ">

可以尝试下预发布版本v0.1.4b1，我用了这个版本后没有重新认证

**Comment by LINJIAXIN-China** [comment]
我也是只有一台HA，也是经常失效

**Comment by refined-fish** [comment]
遇到了同样的问题，大概每3天掉一次，且只登陆了一台HA（后续会需要登录多台HA绑定不同家庭）

**Comment by mmzhi** [comment]
+1 v0.1.3

**Comment by topsworld** [comment]
Hello, you can use the pre-release version v0.1.5b1 to verify whether the relevant issues still exist.
您好，可以使用预发布版本v0.1.5b1验证下相关问题是否还存在

**Comment by jiema** [comment]
遇到了同样的问题
