### ISSUE TITLE
设备中存在RedmiWatch3时,初始化失败

### ISSUE THREAD

**Issue by Dts0** [XiaoMi/ha_xiaomi_home#497]
### Describe the Bug / 描述问题

设备中存在RedmiWatch3时,疑似在初始化配置GPS信息时失败，报错type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'

### How to Reproduce / 复现步骤

1.使用安卓手机在小米运动健康，在小米账号中绑定RedmiWatch3
2.尝试在ha中绑定对应小米账号
3.重启ha即可复现

### Expected Behavior / 预期结果

配置成功，但提示设置失败(没有设备或实体)

### Reproduce Time / 问题复现的时间点

2024-12-29 22:17:00

### Home Assistant Logs / 系统日志

```
2024-12-29T14:06:32.397422875Z 2024-12-29 22:06:32.373 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx: xxx[中国大陆] for xiaomi_home
2024-12-29T14:06:32.397535836Z Traceback (most recent call last):
2024-12-29T14:06:32.397565909Z   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
2024-12-29T14:06:32.397593483Z     result = await component.async_setup_entry(hass, self)
2024-12-29T14:06:32.397618927Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-29T14:06:32.397644278Z   File "/config/custom_components/xiaomi_home/__init__.py", line 265, in async_setup_entry
2024-12-29T14:06:32.397670111Z     raise err
2024-12-29T14:06:32.397695129Z   File "/config/custom_components/xiaomi_home/__init__.py", line 140, in async_setup_entry
2024-12-29T14:06:32.397832441Z     device.spec_transform()
2024-12-29T14:06:32.397871681Z   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 540, in spec_transform
2024-12-29T14:06:32.397891551Z     prop.external_unit = self.unit_convert(prop.unit)
2024-12-29T14:06:32.397909218Z                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-29T14:06:32.397926995Z   File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 630, in unit_convert
2024-12-29T14:06:32.397944976Z     unit_map['μS/cm'] = UnitOfConductivity.MICROSIEMENS_PER_CM
2024-12-29T14:06:32.397963457Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-29T14:06:32.397980939Z AttributeError: type object 'UnitOfConductivity' has no attribute 'MICROSIEMENS_PER_CM'
2024-12-29T14:06:33.335020584Z 2024-12-29 22:06:33.320 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get_device_list, cloud, invalid device, {'did': 'xxx', 'uid': xxx, 'token': 'xxx', 'name': 'Redmi Watch 3', 'pid': 6, 'mac': 'xxx', 'bssid': '', 'longitude': '0.00000000', 'latitude': '0.00000000', 'show_mode': 1, 'model': 'lchz.watch.m65s', 'permitLevel': 16, 'isOnline': False, 'extra': {'isSetPincode': 0, 'pincodeType': 0, 'fw_version': '1.2.73', 'isSubGroup': False, 'showGroupMember': False, 'split': {}}, 'orderTime': 1705806908, 'freqFlag': True, 'hide_mode': 0, 'cnt': 6, 'comFlag': 129, 'carPicInfo': ''}
2024-12-29T14:06:33.335475557Z 2024-12-29 22:06:33.323 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, 691254283
2024-12-29T14:06:33.337978436Z 2024-12-29 22:06:33.324 ERROR (MainThread) [custom_components.xiaomi_home.miot.miot_cloud] get device info failed, x.2069.1510654476.86100c0090020020000023014f24f32a
2024-12-29T14:06:38.402108786Z 2024-12-29 22:06:38.399 ERROR (f1149eeda4fee3e3) [custom_components.xiaomi_home.miot.miot_client] 我的家, mips try reconnect after 12000ms
```

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.10.4

### Home Assistant Operation System Version / Home Assistant Operation System 版本

aarch64 docker homeassistant/home-assistant:stable image-id 2f1cfb37d0fe

### Xiaomi Home Integration Version / 米家集成版本

v0.1.3

### Additional Context / 其他说明

aarch64 rpi4 
docker homeassistant/home-assistant:stable 
image-id 2f1cfb37d0fe

**Comment by topsworld** [comment]
您好，可以尝试下预发布版本v0.1.4b1，正式修复版本这两天会发布

**Comment by Dts0** [comment]
我刚看到，MICROSIEMENS_PER_CM是在Home Assistant 2024.11.0b1里加的，我准备更新下ha版本试试

**Comment by Dts0** [comment]
测试完毕，ha_xiaomi_home更新至v0.1.4b1或ha更新至241220均可解决该问题
