### ISSUE TITLE
Gosund 16A插座连接homekit会出现超时情况

### ISSUE THREAD

**Issue by yanshw** [XiaoMi/ha_xiaomi_home#499]
### Describe the Bug / 描述问题

Homekit无法控制Gosund16开关

### How to Reproduce / 复现步骤

<img width="531" alt="homekit" src="https://github.com/user-attachments/assets/6df3025b-8734-46f8-8537-8944981313cb" />
homekit控制开关插座，homekit端显示开关已经关闭或打开，但是homeassistant中偶尔会出现开关状态无变化的情况

### Expected Behavior / 预期结果

homekit能控制开关

### Reproduce Time / 问题复现的时间点

2024-12-29 22:06:50 

### Home Assistant Logs / 系统日志

日志记录器: homeassistant.core
来源: core.py:2822
首次出现: 22:06:56 (4 次总计出现)
上次记录: 22:07:41

Error executing service: <ServiceCall switch.turn_off (c:01JG9BVD4WRPEBBREYM06B4NTV): entity_id=['switch.cuco_cn_768975410_cp2d_on_p_2_1']>
Error executing service: <ServiceCall switch.turn_off (c:01JG9BVTNV1ZPX7VH3ACA5R003): entity_id=['switch.cuco_cn_768975410_cp2d_on_p_2_1']>
Error executing service: <ServiceCall switch.turn_on (c:01JG9BWR1ZPRSV9VT04Q6QQCFD): entity_id=['switch.cuco_cn_768975410_cp2d_on_p_2_1']>
Error executing service: <ServiceCall switch.turn_off (c:01JG9BWSR3ZC913Z5AFTGTDNED): entity_id=['switch.cuco_cn_768975410_cp2d_on_p_2_1']>
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1077, in set_property_async
    await self.miot_device.miot_client.set_prop_async(
        did=self.miot_device.did, siid=self.spec.service.iid,
        piid=self.spec.iid, value=value)
  File "/config/custom_components/xiaomi_home/miot/miot_client.py", line 658, in set_prop_async
    raise MIoTClientError(
        self.__get_exec_error_with_rc(rc=rc))
custom_components.xiaomi_home.miot.miot_error.MIoTClientError: 执行错误, 设备操作超时

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/switch.py", line 101, in async_turn_off
    await self.set_property_async(value=False)
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1081, in set_property_async
    raise RuntimeError(
        f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 设备操作超时, switch.cuco_cn_768975410_cp2d_on_p_2_1,  开关 开关

### Log Timezone / 日志时区

Asia/Shanghai

### Home Assistant Core Version / Home Assistant Core 版本

2024.12.5

### Home Assistant Operation System Version / Home Assistant Operation System 版本

20241127.8

### Xiaomi Home Integration Version / 米家集成版本

v0.1.4b1

**Comment by SusanPhevos** [comment]
您好！请问 v0.2.4 还有这个问题吗？

**Comment by yanshw** [comment]
> 您好！请问 v0.2.4 还有这个问题吗？

! 你好，升级到v0.2.4之后还是会有这样的提示

<img width="210" alt="Image" src="https://github.com/user-attachments/assets/ab407cf1-3fa2-43d7-a62c-b4cd67ef6c0e" />

<img width="788" alt="Image" src="https://github.com/user-attachments/assets/fa44097b-1c63-4cfc-81f4-43ebba7482e9" />

**Comment by SusanPhevos** [comment]
如果在 Home Assistant 里操作插座开关，会有相同的问题吗？

**Comment by WishTechLab** [comment]
hello，在Home Assistant中操作也会有相同的问题，目前已经升级到最新版本v0.3.2。

![Image](https://github.com/user-attachments/assets/5bed54fc-7903-4804-a32d-53040b361a9e)
![Image](https://github.com/user-attachments/assets/9ecd820f-2583-466b-82fc-b146598c7b81)

**Comment by WishTechLab** [comment]
目前我在使用Xiaomi Miot Auto插件，这个插件完全没有问题。
如果Xiaomi Home插件有问题的话，就是启用Miot插件。请问这两个能否共存。

![Image](https://github.com/user-attachments/assets/3690f770-66d0-4260-b145-41201cbbc3b5)
