### ISSUE TITLE
[Bug]: 杜亚窗帘的控制功能始终处于不可用的状态

### ISSUE THREAD

**Issue by A-Cepheus** [XiaoMi/ha_xiaomi_home#85]
### Describe the bug / 描述问题

型号杜亚M1、M2，其他信息和开关正常，唯独开合控制处于不可用

### To Reproduce / 复现步骤

添加账号与设备后即处于不可用状态

### Expected behavior / 预期结果

应该是可以控制打开和关闭的

### Home Assistant Logs / 系统日志

可能相关的日志：
2024-12-17 07:20:20.714 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback MIoTServiceEntity.__write_ha_state_handler() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 965, in __write_ha_state_handler
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 322, in state
    if self.is_opening:
       ^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/cover.py", line 226, in is_opening
    prop=self._prop_status) == self._prop_status_opening
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Cover' object has no attribute '_prop_status_opening'

### Home Assistant Core version / Home Assistant Core 版本

2024.12.1

### Home Assistant Operation System version / Home Assistant Operation System 版本

docker

### Xiaomi Home integration version / 米家集成版本

v0.1.0

### Additional context / 其他说明

![image](https://github.com/user-attachments/assets/6178827b-3d0d-4740-b189-3c8c98e002c4)

**Comment by topsworld** [comment]
好的，问题下个版本修复

**Comment by A-Cepheus** [comment]
WFM, thanks!
