### ISSUE TITLE
[Bug]: tts问题

### ISSUE THREAD

**Issue by foxwywh** [XiaoMi/ha_xiaomi_home#97]
### Describe the bug / 描述问题

两个家，两台ha，两个网段并且通过广域网组成一个“局域网”，小爱tts其中有一个会报错。

### To Reproduce / 复现步骤

无法执行动作“text.set_value” 。 Unknown error

### Expected behavior / 预期结果

希望修复

### Home Assistant Logs / 系统日志

无

### Home Assistant Core version / Home Assistant Core 版本

2024.12.3

### Home Assistant Operation System version / Home Assistant Operation System 版本

2024.12.3

### Xiaomi Home integration version / 米家集成版本

V0.1.0

### Additional context / 其他说明

无

**Comment by SusanPhevos** [comment]
您好！请发一下复现问题时的Home Assistant日志。

**Comment by foxwywh** [comment]
日志记录器: homeassistant.helpers.script.websocket_api_script
来源: /usr/src/homeassistant/homeassistant/helpers/script.py:2030
首次出现: 20:14:46 (1 次总计出现)
上次记录: 20:14:46

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 执行错误, 内部错误, text.xiaomi_cn_604264054_lx06_play_text_a_5_1, 智能音箱 播放文本
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1032, in entity_service_call
    raise result from None
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1628, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/text/__init__.py", line 81, in _async_set_value
    await entity.async_set_value(value)
  File "/config/custom_components/xiaomi_home/text.py", line 153, in async_set_value
    if await self.action_async(in_list=in_value):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_home/miot/miot_device.py", line 1285, in action_async
    raise RuntimeError(f'{e}, {self.entity_id}, {self.name}') from e
RuntimeError: 执行错误, 内部错误, text.xiaomi_cn_604264054_lx06_play_text_a_5_1,  智能音箱 播放文本
